const zh = {
  qrPay: {
    text: "一個開創性的支付協會，將整個支付生態系統聯合起來，無縫連接加密貨幣和現實世界的交易。",
    supportText: "支持付款方式：",
    btnText: "掃描二維碼支付"
  },
  headerTitle: {
    GoogleAuthenticator: '穀歌身份驗證器',
    DownloadAPP: "下載APP",
    Settings: "設定",
    Transactiondetails: "交易詳情",
    Refunddetails: "退款詳情",
    Depositdetails: "存款明細",
    Withdrawdetails: "提款詳細資訊",
    Managebalance: "管理餘額",
    Deposit: "存款",
    Withdraw: "提款",
    History: "歷史",
    Payment: "付款"
  },
  settings: {
    General: '概述',
    Security: '安全',
    DisplayedCurrency: '顯示的貨幣',
    Language: '語言',
    Email: '電子郵件',
    GoogleAuthenticator: '穀歌身份驗證器',
    LogOut: '註銷',
    Activate: '啟動',
  },
  logout: {
    msg: '您是否要登出？',
    Cancel: '取消',
    Confirm: '確認',
  },
  // 邮箱
  email: {
    VerificationMethod: '驗證方法',
    EmailVerification: '電子郵件驗證',
    GoogleAuthenticator: 'Google身份驗證器',
    verification_title: '請輸入發送到以下位址的驗證代碼',
    verification_title1: 'Google身份驗證器代碼',
    Sendcode: '發送代碼',
    Notreceived: '未收到？',
    Resendcode: '重新發送代碼',
    countDawn: '已發送新的驗證代碼',
  },

  // cvv  查看卡信息
  viewCardInfo: {
    CardNumber: '卡號',
    Expired: '過期',
    Address: '地址',
    CVV: 'CVV',
    Cardholder: '持卡人',
    btn: '返回首頁',

    street: '街道',
    city: '城市',
    state: '州',
    country: '國家',
    zipCode: '郵遞區號',
  },

  // 无卡首页
  noCardHome: {
    applyBtn: '申請您的第一張卡片',
    tabType1: '交易',
    tabType2: '充值',
    more: '更多',
    noTransactions: '暫無交易',
    noTransactionsInfo: '將您的卡片添加到支付平臺或網站上',
    noTopped: '您尚未充值',
    noToppedInfo: '請完成第一次充值以啟動卡片',
    poweredBy: '由...提供支持',
  },

  BinancePay: {
    title: 'Binance支付',
    info: '使用您的Binance帳戶進行轉帳',
    title1: '代幣支付',
    info1: '使用您的其他錢包進行轉帳',
    title2: 'Gate支付',
    info2: '使用您的Gate帳戶進行轉賬',
    title3: '代金券',
    info3: '使用代金券充值',
  },

  paymentMethod1: {
    exchange: '交易所',
    instant: '立即',
    support: '支持',
    cryptoCurrency: '加密轉帳',
    mins: '分鐘',

    gatePay: 'Gate 支付',
    gatetip: '使用您的 Gate 帳戶或 Defi 錢包進行轉賬',
    chainUpPay: '快速支付',
    chainUpTip: '使用您的快速支付進行轉帳',

    noListInfo: '无可用的代币，请调整金额。',
  },

  gatePay: {
    result: {
      title: 'Gate支付',
      info1: '支付成功',
      info2: '支付失败',
      btn: '關閉',
    },
  },

  countryWarning: {
    tip: '使用者國家限制警告！',
    details: '詳情',
    tipTitle: '重要提醒',
    tipDetail1: '您當前所在的國家受到限制。請在60天內從您現有的卡帳戶中提取現金並刪除該卡。',
    tipDetail2: '如果60天後餘額仍未提取完畢，我們將凍結該帳戶。',
    btn: '我已閱讀並同意',
  },

  // 申请卡类型弹窗
  applyCardType: {
    title: '選擇卡類型',
    card: '加密卡',
    KYC: 'KYC',
    verifyKYC: '驗證KYC',
    noKYC: '無需KYC',
    applyfee: '申請費',
    rechargeFee: '充值費',
    limitMonth: '每月充值限額',
    Pay: '支付',
    title1: '選擇付款方式',
    title2: '選擇您要支付的代幣',
    title3: '請選擇付款方式',
    confirm: '確認',
  },

  // applyCard 卡申请
  applyCard: {
    title: '卡片',
    liteCard: '輕量卡',
    standardCard: '標準卡',
    applyList1: '使用加密貨幣充值',
    applyListinfo1: '使用您的加密貨幣進行快速的美元充值',
    applyList2: '在全球範圍內以美元消費',
    applyListinfo2: '可用于任何美元支付場景，並可與Apple Pay綁定',
    applyList3: '較低費用',
    applyListinfo3: '與傳統信用卡相比，費用較低。無年費或逾期付款費',
    applyFee: '申請費',
    limitMonth: '每月充值限額',
    consumptionFee: '消費費用',
    KYC: 'KYC',
    verifyKYC: '驗證KYC',
    noKYC: '無需KYC',
    rechargeFee: '充值費',
    asLowAs: '最低只需',
    termsOfValidity: '有效期條款',
    year: ' 年',
    btn: '預訂您的卡片',

    identifyVerification: '身份驗證',
    no: '否',
    yes: '是',
    restrictedUsages: '受限使用',
    subTitle: '請選擇付款方式',
  },

  // informationSubmit 卡信息提交
  informationSubmit: {
    title: '申請卡片',
    title1: '請輸入您的資訊',
    FirstName: '名字（請輸入英文）',
    FirstNamePlaceholder: '英文名字',
    LastName: '姓氏（請輸入英文）',
    LastNamePlaceholder: '英文姓氏',
    title2: '請完成您的首次充值',
    tip1: '最低 ',
    tip2: ' 可以啟動您的卡片',
    Rechargeamount: '充值金額',
    tipPop: '您想要充值到卡片餘額的金額',
    btn: '確認',
    maxErrTip: '金額超過最大限額',
    minErrTip: '金額低於最小限額',
    nameErrTip: '請輸入有效的姓名。',
    nameErrTip1: '請輸入有效的姓名。',
    nameFirErrTip: '名字的长度限制为15个字符',
    nameLastErrTip: '姓氏的长度限制为15个字符',
    tip: '使用卡片的說明',
    info1: '1.如果您連續進行五次或更多筆面額為 0 美元的交易，您的卡片或帳戶可能會被暫時凍結。',
    info2: '2.請不要綁定任何支付金融產品、加密貨幣和其他高風險平台。',
    info3: '3.請避免因以下原因導致您的卡片交易被拒絕，因為多次拒絕可能導致卡片或帳戶被凍結。原因包括：不允許國際購買，商戶類別代碼（MCC）不允許，MCC 不可用，MCC 無效，無效處理代碼。',
    info4: '4.我們可能在我們自行決定的情況下允許您的卡片透支。然而，根據您帳戶上任何時候存在的透支余額金額，我們可能收取透支費用，並從您的帳戶中扣除。您應當在要求時支付給我們此類透支金額和費用。',
    info5: '5.請避免高頻交易拒絕。如果拒絕率超過 15%，並且連續三次拒絕，您的卡將被取消。',
    info6: '6.請勿在發卡銀行禁止的商戶類型處使用您的卡片進行交易，否則可能導致卡片凍結或註銷。',
    info6_1: '查看受限制的商戶類別。',
    info7: '7.该卡不接受超额退款，即超过原交易金额的退款。如果卡片被取消或删除，则无法收到退款。',
  },

  // paymentCard 选择token
  paymentCard: {
    title: '申請卡片',
    title1: '選擇代幣並充值您的卡片',
    rechargeCountDown: '您將支付',
    rechargeCountDown1: '以進行充值',
    Applyfee: '申請費',
    Rechargefee: '充值費',
    Pay: '支付',
    applyFee: '申請費',
    limitMonth: '每月充值限額',
    consumptionFee: '消費費用',
    KYC: 'KYC',
    verifyKYC: '驗證KYC',
    noKYC: '無需KYC驗證',
    shippingFee: '運費',
    rechargeFee: '充值費',
    termsOfValidity: '有效期條款',
    year: ' 年',
    errTip: '系統異常',
    sheetListTitle: '選擇加密貨幣',
  },

  // payDeposit 创建卡详情页
  payDeposit: {
    title: '卡片充值',
    Paymentamount: '支付金額',
    tip: '此金額不包括您進行交易時的網路費用。例如，訂單金額為100 USDT，而您選擇的網路為Trc20，如果您使用中心化交易所提取，您最終需要轉帳101 USDT。',
    RechargeAddress: '充值地址',
    payDepositTip1: '1. 請確保充值金額與訂單金額一致，否則會導致資金損失',
    payDepositTip2: '2. 平均到賬時間：5分鐘~10分鐘',
    payDepositTip3: '3. 此地址僅接受 ',
    payDepositTip4: '4. 請不要向此地址充值任何其他資產',
    payDepositTip5: '5. 一個地址只能充值一次，請勿保存截圖並重複使用',
    countDownTip: '請在此時間內完成轉賬',
    Done: '完成',
  },

  // 进行中
  padding: {
    Crypto_Sending: '加密貨幣正在發送中...',
    Payment_successed: '付款成功',
    generated: '加密虛擬卡片正在生成中',
    tip: '加密虛擬卡片生成成功 虛擬卡片生成成功',
  },

  // 成功
  success: {
    Application: '申請成功！',
    Payment_successed: '付款成功',
    generated: '虛擬卡片已成功激活',
    Cardholder: '持卡人',
    CardNumber: '卡號',
    Balance: '餘額',
    IssuingDate: '發卡日期',
    btn_text: '返回首頁並開始使用',
  },

  // 失败
  failed: {
    Application: '申請失敗',
    Payment_successed: '付款成功',
    Failed_reason: '失敗原因',
    Application_Failed_content: '您的真實存款金額低於我們的限額（5美元），請檢查公告電子郵件並獲取退款。',
    btn_text: '返回首頁',
    Recharge: '充值失敗',
    Recharge_completed: '充值完成',
    Recharge_Failed_content: '您的真實存款金額低於我們的限額（5美元），請檢查公告電子郵件並獲取退款。',
  },

  // 超时
  timeout: {
    Order_timeout: '訂單已超時！',
    Back_home: '返回首頁',
  },

  binancePayPage: {
    tip1: '請稍候。我們正在將您重定向到您選擇的支付網關。',
    note: '注意：',
    note1: '如果無法顯示支付網關頁面，請按立即支付按鈕完成訂單並進行付款。',
    payNow: '立即支付',
  },

  // 无效 invalidPage
  invalid: {
    tip: '所請求的頁面無效。',
    tip1: '请在您的KYC结果中进行检查 ',
    tip2: 'Telegram Bot',
    tip3: ' 請使用聊天框並繼續進行後續操作。',
    btn: '返回Alchemy Pay',
  },

  cardAmountNote: {
    tip1: '注意：用户最多可以创建',
    tip2: '張虛擬卡，包括已刪除的卡。',
  },

  // KYC相关页面
  KYC: {
    title1: '申請卡片',
    title2: '升級',
    subtitle_Verify: 'KYC驗證',
    text: '以下是您接下來要做的事情',
    content_title1: '驗證您的身份證明文件',
    content_text1: '當您與我們開設賬戶時，您需要向我們出示您的身份證明文件。請確保您選擇的國家與您提供的文件相同。',
    content_title2: '驗證您的自拍照片是否匹配',
    content_text2: '我們將進行臉部動態識別驗證。',
    btn_text: '開始',
    tip1: '欧洲经济区（EEA）: 包括',
    tip2: '奧地利、比利時、保加利亞、克羅地亞、塞浦路斯共和國、捷克共和國、丹麥、愛沙尼亞、芬蘭、法國、德國、希臘、匈牙利、愛爾蘭、意大利、拉脫維亞、立陶宛、盧森堡、馬爾他、荷蘭、波蘭、葡萄牙、羅馬尼亞、斯洛伐克、斯洛文尼亞、西班牙、瑞典、冰島、列支敦士登和挪威。',

    content_text1_1: '請確保上傳文件的角落完整。',
    content_text2_1: '請確保在面部動態識別認證期間直視攝像頭。',
  },

  // onfidoKyc kyc 验证
  onfidoKyc: {
    title1: '申請卡片',
    title2: '升級',
    subtitle_Verify: 'KYC驗證',
    text: '以下是您接下來要做的事情',
  },

  // kycStatus kyc 状态
  kycStatus: {
    title: '身份證明和自拍照片',
    UnderReview: '審核中...',
    waittingFor: '您已等待：',
    inVerification: '驗證中',
    btn1: '完成',
    btn2: '更新文件',
    statusTitle1: '身份驗證成功',
    statusText1: '恭喜！所有提交的文件已通過驗證。',
    statusTitle2: '重新提交相關文件',
    statusText2: '',
    statusTitle3: '身份驗證被拒絕',
    statusText3: '',
    statusTitle4: '您提交的文件正在審核中。',
    statusText4: '',
  },

  // faq  页面
  faq: {
    title: 'Alchemy Pay 卡片常見問題。',
    faqItemTitle1: '加密貨幣卡是信用卡嗎？',
    faqItemInfo1: '不是，加密貨幣卡是一張預付借記卡，具有固定金額，不支援透支限額。',
    faqItemTitle2: '支援哪些貨幣和網絡類型進行充值？',
    faqItemInfo2: '目前，我們支援USDT、USDC、BTC、ETH和平台幣進行充值。支援的網絡包括Trc20、Bep20、Erc20、Sol和比特幣。',
    faqItemTitle3: '使用加密貨幣卡支援的法定貨幣和國家有哪些？',
    faqItemInfo3: '加密貨幣卡的貨幣是美元，支援全球范圍內的網上支付。',
    faqItemTitle5: '金額有限制嗎？',
    faqItemInfo5: '有每月充值限額。LITE卡為100美元，標準卡為2000美元。',
    faqItemTitle5_1: '封鎖加密貨幣卡服務使用的司法管轄區。',
    faqItemInfo5_1: 'Alchemy Pay不會向任何不接受加密貨幣國家的任何個人或實體提供加密貨幣卡服務。這意味著這些國家的任何個人或實體將被禁止使用Alchemy Pay的加密貨幣卡服務。以下是不接受加密貨幣不友好國家：阿爾及利亞、孟加拉國、玻利維亞、中國（中華人民共和國）、厄瓜多爾、馬其頓和尼泊爾。',
    faqItemTitle6: '如何查看我的加密貨幣卡的帳單地址？',
    faqItemInfo6: '在卡片管理主頁上點擊“卡片信息”以獲取CVV和帳單地址信息。',
    faqItemTitle7: 'LITE卡可以升級到標準卡嗎？',
    faqItemInfo7: '目前不支援，但將在下一個版本中提供。如果您已經有LITE版本卡且想提高限額，您可以取消LITE卡，然後重新申請標準卡。',
    faqItemTitle8: '如果我充錯了貨幣或網絡該怎麼辦？',
    faqItemInfo8: '由於我們涉及金融機構，請不要嘗試這樣的測試，因為可能無法恢復。在充值時，請確保選擇正確的貨幣和網絡。',
    faqItemTitle9: '為什麼實際充值餘額與設定的金額不同？',
    faqItemInfo9: '在ACH收到用戶支付後，會即時將其賣出成USDT，扣除相關費用，按1:1比例充值到加密貨幣卡中。如果用戶選擇的貨幣波動較大或支付過程時間較長，實際充值金額可能略低或略高於設定的充值金額。',
    faqItemInfo9_1: '如果加密貨幣價格大幅波動，實際充值金額小於5美元，則充值訂單將失敗，系統將通過電子郵件通知用戶啟動退款流程。',
    faqItemTitle10: '卡片余額可以提取嗎？',
    faqItemInfo10: '是的，我們支援將卡片余額提取為USDT。',
    faqItemTitle11: '充值需要多長時間？',
    faqItemInfo11: '充值時間取決於您選擇的網絡和網絡狀況。通常，充值時間範圍從5分鐘到1小時不等。',
    faqItemInfo11_1: '如果您的充值時間較長且尚未到賬，請向工作人員發送您的註冊電子郵件、充值地址和哈希以進一步查詢。',
    faqItemTitle12: '支付退款需要多長時間？',
    faqItemInfo12: '退款涉及國際結算，需3-7個工作日處理。',
    faqItemInfo12_1: '請避免惡意退款。如果判定退款為惡意，銀行和合規部門將對卡片採取某些限制措施。',
    faqItemTitle13: '如果支付狀態一直處於待定狀態該怎麼辦？',
    faqItemInfo13: '如果交易記錄中的支付狀態顯示為“待定”，可能是由於結算時間問題，並不意味著交易失敗。它只是處於處理狀態。與國內加密貨幣卡不同，海外加密貨幣卡的結算不是實時的，通常需要約24-48小時的結算周期，極特殊情況下可能需要更長的時間。',
    PoweredBy: '技術支持',
  },

  // termsOfService 页面
  termsOfService: {
    title: '使用條款',
    updatedTime: '最後更新日期：2024年5月3日',

    head_desc:
      '這些Bit.Store Web3 Cards的使用條款（以下簡稱“協議”），連同費用政策、隱私政策和本網站上顯示的任何其他適用條款和條件（以下簡稱“協議”），規範您（即Bit.Store Web3 Card的持有人，以下簡稱“持卡人”或“您”）與我們Bitstore Europe UAB（以下簡稱“Bitstore”、“我們”或“我們的”）之間的關係，以及您通過本網站和/或API（統稱為“網站”）使用Bit.Store Web3 Card服務（以下簡稱“卡服務”）。',
    head_desc1_1: '',
    head_desc1_2: '',
    head_desc1_3: '',

    head_desc1_4: '',
    head_desc1_5: '',

    head_desc1_6: '',

    head_desc1_7: '',

    head_desc1_8: '',

    head_desc1_9: '',
    head_desc1_9_1: '',
    head_desc1_9_2: '',
    head_desc1_10: '',
    head_desc1_11: '',
    head_desc1_12: '',
    head_desc1_13: '',

    head_desc1_14: '',
    head_desc1_15: '',
    head_desc1_16: '',
    head_desc1_17: '',
    head_desc1_18: '',

    head_desc2: '為免產生疑問，協議在Bitstore接受持卡人提交的申請並將卡片發行給持卡人後達成並生效。',

    paragraphTitle1: `1. 定義`,
    desc1: '使用以下定義：',
    paragraphInfo1_1: '帳戶：',
    paragraphInfo1_2: 'Bitstore為持卡人開立和維護的帳戶；',
    paragraphInfo1_3: '申請：',
    paragraphInfo1_4: '持卡人通過網站向Bitstore提交的訂購卡片的申請；',
    paragraphInfo1_5: '工作日：',
    paragraphInfo1_6: '除立陶宛的星期六、星期天或公共假期或銀行假期以外的任何一天；',
    paragraphInfo1_7: '卡片',
    paragraphInfo1_7_1: '或',
    paragraphInfo1_7_2: 'Bit.Store',
    paragraphInfo1_7_3: 'Web3卡：',
    paragraphInfo1_8: '由發卡機構向持卡人發行的支付工具。該術語可指實體卡或虛擬卡；',
    paragraphInfo1_9: '發卡機構：',
    paragraphInfo1_10: '任何國際卡組織的成員銀行或金融機構，授權Bitstore提供訪問服務，以便持卡人申請並使用卡片。',
    paragraphInfo1_11: '持卡人：',
    paragraphInfo1_12: '持有卡片並被授權使用卡片的人；',
    paragraphInfo1_13: '服務費：',
    paragraphInfo1_14: ' 與卡片發行、貨幣兌換和支付交易相關的費用，包括但不限於在“費用和限額”頁面上公開的那些費用。',
    paragraphInfo1_15: '國際卡組織：',
    paragraphInfo1_16: '國際支付卡組織，如MasterCard或VISA；',
    paragraphInfo1_17: '身份驗證方式：',
    paragraphInfo1_18: '由發卡機構提供給持卡人的持卡人數據、卡片數據（CVV、有效期等）、PIN碼和/或其他方式，使持卡人能夠進行身份驗證並發起操作，包括但不限於在線支付交易；',
    paragraphInfo1_19: '商家：',
    paragraphInfo1_20: '與Bitstore達成合作協議的第三方，用於分發卡片和向最終用戶提供卡片服務；',
    paragraphInfo1_21: '支付交易：',
    paragraphInfo1_22: '由持卡人使用卡片發起的資金存入、轉賬或提取。',

    paragraphTitle2: `2. Bit.Store Web3卡及卡片服務`,
    paragraphInfo2_1: '2.1  Bit.Store Web3卡由持有國際卡組織許可的發卡機構發行。要符合申請Bit.Store Web3卡的資格，您必須年齡在18至65歲之間，並居住在我們批准的國家之一。',
    paragraphInfo2_2: '2.2  您可以通過網站使用法定貨幣或數字貨幣（如USDT等）充值您的Bit.Store Web3卡，具體取決於卡片類型。為明確起見，充值到卡片或帳戶的資金不計利息。',
    paragraphInfo2_3: '2.3  您可以在全球範圍內的在線平台或某些支持Mastercard和/或Visa支付的線下支付場景中使用卡片，具體視發卡機構和/或相應國際卡組織的要求而定，可能會不時變更。',
    paragraphInfo2_4: '2.4  發卡機構可以隨時取消、撤銷、收回或限制卡片的使用。Bitstore可能會因任何原因拒絕授權或撤銷交易或暫停卡片，包括但不限於違反協議、涉嫌欺詐以及持卡人的信用狀況。Bitstore也可能拒絕授權發卡機構指定的商家的支付交易。Bitstore不對因拒絕或撤銷支付交易而導致的損失負責。',

    paragraphTitle3: '3. 服務費',
    paragraphInfo3_1: '3.1 持卡人應支付在我們的“費用和限額”頁面上描述的卡片發行和使用服務費，這些費用可能會根據Bitstore的自行決定不時更新。',
    paragraphInfo3_2: '3.2 所有支付交易的服務費將由Bitstore從帳戶中扣除。',
    paragraphInfo3_3: '3.3 Bitstore決定阻止卡片的行為不應被視為終止協議。因此，阻止卡片的行為，即拒絕進行支付交易，不應免除持卡人支付所提供服務的任何服務費的義務。',

    paragraphTitle4: '4. 卡片發行和交付',
    paragraphInfo4_1: '4.1  為了接收卡片，持卡人必須通過網站或商家向Bitstore提交申請。',
    paragraphInfo4_2: '4.2  Bitstore在接受持卡人的申請後將發行卡片。如果是實體卡，商家或Bitstore（如適用）應在Bitstore接受申請後負責將實體卡片交付給持卡人。',
    paragraphInfo4_3: '4.3  持卡人在卡片發行後，應獲得獨特的身份驗證方式。此類身份驗證方式被視為持卡人簽名，以執行支付交易。使用身份驗證方式應被視為同意和授權進行支付交易。',

    paragraphTitle5: '5. 卡片支付',

    paragraphInfo5_1: '5.1 僅持卡人有權使用卡片進行支付交易。',
    paragraphInfo5_2: '5.2 持卡人可以進行支付交易：',
    paragraphInfo5_2_1: 'a) 虛擬卡發行後立即；',
    paragraphInfo5_2_2: 'b) 實體卡成功交付並激活後。',
    paragraphInfo5_3: '5.3 持卡人僅能在帳戶中存有的金額範圍內並根據協議中規定的卡片使用限額（如每月支付交易的最高金額、風險控制的卡片限額等）進行支付交易。Bitstore保留不時自行決定確定卡片使用限額的權利。',
    paragraphInfo5_4: '5.4 除非證明相反，Bitstore假定所有支付交易均由持卡人同意、授權和發起。',
    paragraphInfo5_5: ' 5.5 使用卡片或身份驗證方式發起支付交易應被視為授權並同意進行支付交易。除非為保護消費者權益另有規定，持卡人同意進行支付交易後，除非收款人同意退還金額，否則持卡人無權要求退款。',
    paragraphInfo5_6: '5.6 如果發卡機構確定持卡人的卡片接收到或可能接收到不成比例的交易被拒絕、逆轉、退款、爭議、費用或其他責任，持卡人將會通過電子郵件通知需要支付某些處理費用。如果持卡人不同意支付這些費用，則可能會被拒絕使用卡片服務。',
    paragraphInfo5_7: '5.7 持卡人使用卡片進行的付款交易可能會被拒絕，如果：',
    paragraphInfo5_7_1: 'a) 卡片無效或被阻止；',
    paragraphInfo5_7_2: 'b) 發卡機構或 Bitstore 已關閉、暫停或限制了持卡人的帳戶；',
    paragraphInfo5_7_3: 'c) 進行付款交易所需的資金超過了持卡人帳戶上的可用資金；',
    paragraphInfo5_7_4: 'd) 付款交易超過了卡片使用限制；',
    paragraphInfo5_7_5: 'e) 根據協議或法律行為，或者懷疑持卡人進行欺詐或其他非法活動。',
    paragraphInfo5_8: '5.8 Bitstore 保留使用第三方服務來確保付款交易或其他卡片服務執行的權利。',

    paragraphTitle6: '6. 持卡人的義務以確保卡片安全使用',

    paragraphInfo6_1: '6.1 持卡人有以下義務以確保卡片安全使用：',
    paragraphInfo6_1_1: 'a) 在使用之前啟用實體卡片。此過程應在收到實體卡片後進行。持卡人應對由於提前啟用或未遵循卡片啟用指示而造成的任何損失負責；',
    paragraphInfo6_1_2: 'b) 防止卡片遭受任何物理損壞（針對實體卡），包括複製、修改等；',
    paragraphInfo6_1_3: 'c) 遵守 Bitstore、發卡機構和/或相應的國際卡片組織提供的程序和指示，以及協議中描述的其他要求；',
    paragraphInfo6_1_4: 'd) 立即通知 Bitstore 任何妨礙付款交易執行的故障；',
    paragraphInfo6_1_5: 'e) 保持帳戶上有足夠的資金以支付服務費和進行付款交易；',
    paragraphInfo6_1_6: 'f) 除非法律或發卡機構或 Bitstore 要求，否則不得將卡片提供給任何第三方；',
    paragraphInfo6_1_7: 'g) 保護卡片和/或身份驗證方式免於任何未經授權的使用、丟失、被盜或洩露給任何第三方，並立即通知 Bitstore 發生此類事件以防止持卡人進一步損失；',
    paragraphInfo6_1_8: 'h) 不在批准的國家/地區之外使用卡片，亦不從事任何非法活動，包括購買適用法律禁止的商品/服務；',
    paragraphInfo6_1_9: 'i) 立即通知 Bitstore 持卡人的個人信息變更；以及',
    paragraphInfo6_1_10: 'j) 遵守協議中規定的或 Bitstore、發卡機構和/或相應的國際卡片組織不時要求的任何其他義務。',

    paragraphTitle7: '7. 卡片取消',
    paragraphInfo7_1: '7.1 發卡機構將自行決定卡片取消的規則。如果持卡人對卡片取消有任何疑問，應向 Bitstore 或商家詢問。',
    paragraphInfo7_2: '7.2 為清楚起見，當卡片被停用時，根據卡片類型和發卡機構的規則，可能會從帳戶餘額中扣除某些費用。',

    paragraphTitle8: '8. 有效性和卡片封鎖',
    paragraphInfo8_1: '8.1 如果帳戶被關閉，則卡片被視為過期，因此，自帳戶關閉時起卡片不再有效。',
    paragraphInfo8_2: '8.2 為了核實卡片使用的情況，Bitstore 保留在以下情況下封鎖卡片使用的權利：',
    paragraphInfo8_2_1: 'a) 身份驗證方式已洩露給無權使用卡片的人；',
    paragraphInfo8_2_2: 'b) 帳戶被取消、關閉、暫停或限制；',
    paragraphInfo8_2_3: 'c) 卡片在批准國家/地區之外的司法管轄區使用；',
    paragraphInfo8_2_4: 'd) 持卡人進行付款交易的活動可能與欺詐或任何其他非法活動有關；',
    paragraphInfo8_2_5: 'e) 持卡人未適當履行任何義務；或',
    paragraphInfo8_2_6: 'f) Bitstore 認為有其他重要理由封鎖卡片。',
    paragraphInfo8_3: '8.3 如果卡片封鎖的原因依然存在，Bitstore 有權封鎖卡片。',
    paragraphInfo8_4: '8.4 持卡人有權隨時要求封鎖卡片。',
    paragraphInfo8_5: '8.5 除非法律另有規定，Bitstore 不對持卡人或其他第三方因卡片封鎖造成的任何類型的損害負責。',

    paragraphTitle9: '9. Bitstore 在防止洗錢和資助恐怖主義方面的權利',
    paragraphInfo9_1: '9.1 Bitstore 根據立陶宛和其他適用的洗錢和資助恐怖主義法律，擁有以下權利：',
    paragraphInfo9_1_1: 'a) 交換持卡人的信息和文件以確保防止洗錢和資助恐怖主義；',
    paragraphInfo9_1_2: 'b) 定期驗證持卡人的身份信息，並隨時要求持卡人提交額外文件；',
    paragraphInfo9_1_3: 'c) 對持卡人進行付款交易施加臨時或永久限制；',
    paragraphInfo9_1_4: 'd) 要求提供有關持卡人付款交易或任何其他卡片使用的任何類型的文件和信息；',
    paragraphInfo9_1_5: 'e) 要求提供有關參與持卡人付款交易的任何人的文件和信息；',
    paragraphInfo9_1_6: 'f) 要求提供任何其他類型的文件和信息以確保 Bitstore 履行防止洗錢和資助恐怖主義的責任；以及',
    paragraphInfo9_1_7: 'g) 如果持卡人不遵守防止洗錢和資助恐怖主義的要求，有權拒絕執行付款交易或任何其他卡片使用。',

    paragraphTitle10: '10. 責任',
    paragraphInfo10_1: '10.1 持卡人對違反協議或任何其他法律行為中規定的任何義務負全部責任。',
    paragraphInfo10_2: '10.2 Bitstore 對第三方參與處理付款交易不承擔責任。此外，Bitstore 不對第三方拒絕接受卡片支付商品或服務負責。',
    paragraphTitle11: '11. 最終條款',
    paragraphInfo11_1: '11.1 本協議受立陶宛法律管轄，不考慮法律衝突原則。雙方不可撤銷地同意提交立陶宛法院的專屬管轄。雙方進一步同意，任何由你或任何第三方提起的因本協議或你使用卡片或卡片服務而引起的訴訟，必須在訴因發生後一年內開始，否則該訴因將永久禁止。',
    paragraphInfo11_2: '11.2 Bitstore 有權向法律有權接收此類信息的第三方披露持卡人執行的付款交易信息。',
    paragraphInfo11_3: '11.3 本協議將公佈在 Bitstore 和/或商家的網站上，並可能不時更新。持卡人特此同意定期查看本協議以了解任何變更。',
  },
  // termsOfService 页面
  termsOfService1: {
    title: '使用條款',
    paragraphTitle1: '通用條款',
    paragraphInfo1_1: 'Alchemy Pay加密貨幣卡協議（本“協議”，以及通用條款、我們的費用政策、隱私政策和我們網站上顯示的任何其他適用的條款和條件：',
    paragraphInfo1_2: 'https://www.alchemypay.org/terms-of-use',
    paragraphInfo1_3: '十分重要，因為它們共同構成您（即Alchemy Pay加密貨幣卡的持有人，“客戶”）與我們（“Alchemy Pay”或“我們”）之間就使用Alchemy Pay加密貨幣卡達成法律約束的協議。它還列出了您需要了解的其他重要事項。',
    paragraphInfo1_4: '客戶確認並同意，在申請過程中勾選“Alchemy Pay加密貨幣卡”框時，它表明其意愿簽署這些條款和條件，並且構成了客戶與Alchemy Pay之間的協議。',
    paragraphTitle2: '目的',
    paragraphInfo2_1: 'Alchemy Pay加密貨幣卡（無實體卡）是一種預付卡，支援用戶使用USDT、USDC、BTC、ETH直接充值美元金額。',
    paragraphInfo2_2: '它可以用於全球支援Mastercard付款的在線平台（如亞馬遜、易趣等），並可以連接到Apple Pay以進行離線支付。',
    paragraphTitle3: '費用和收費：',
    paragraphInfo3_1: '支援Mastercard功能。',
    paragraphInfo3_2: '根據卡片類型需要進行KYC驗證。',
    paragraphInfo3_3: '申請費用取決於卡片類型。',
    paragraphInfo3_4: '無月費。',
    paragraphInfo3_5: '存在充值費用。',
    paragraphInfo3_6: '每月限額和充值限額因情況而異。',
    paragraphInfo3_7: '最低充值金額為10美元。',
    paragraphInfo3_8: 'Alchemy Pay加密貨幣卡不是銀行賬戶，通過加密貨幣進行的資金充值不產生利息。',
    paragraphTitle4: '提款程序',
    paragraphInfo4_1: '用戶可以通過USDT或商戶平台代幣提取加密貨幣卡賬戶中的任何未使用余額。',
    paragraphInfo4_2: '最低可兌換金額為10美元。',
    paragraphInfo4_3: '兌換的最短時間間隔為48小時。',
    paragraphTitle5: '使用Alchemy Pay加密貨幣卡',
    paragraphInfo5_1: '5.1 每個用戶只能申請一張Alchemy Pay加密貨幣卡。',
    paragraphInfo5_2: '5.2 Alchemy Pay可能自行決定並調整特定加密貨幣卡的最大數量、每月限額和卡片限額，以便從時間到時間進行風險控制和合規監管。任何超過此額度的支付將被拒絕。',
    paragraphInfo5_3:
      '5.3 所有Alchemy Pay加密貨幣卡均為服務提供者的財產，並在要求時必須歸還。服務提供者可以隨時取消、撤銷、收回或限制使用加密貨幣卡。Alchemy Pay可能因違反本協議、涉嫌欺詐或信用情況而拒絕授權或撤銷收費，或者暫停加密貨幣卡的使用。Alchemy Pay還可能拒絕在服務提供者所特定的商戶進行授權交易。Alchemy Pay不對因交易被拒絕或撤銷而導致的損失負責。',
    paragraphInfo5_4: '5.4 如果服務提供者確定客戶的加密貨幣卡接收到或可能接收到過多的交易拒絕、撤銷、退款、爭議、費用或其他負債，客戶可能會收取某些處理費用，並通過電子郵件通知。客戶如果不同意支付此類費用或收費，可停止使用服務。',
    paragraphInfo5_5: '5.5 卡片賬戶本身受到複雜的銀行級安全系統保護，確保資金得到充分保護。每次用戶發起CVV或地址信息請求時，都會經過安全驗證。用戶還可以在安全驗證后輕松取消加密貨幣卡，將余額返回到自己的加密錢包。我們不建議用戶在任何情況下分享他們的CVV碼。',
    paragraphInfo5_6:
      '5.6 客戶應負責保護賬戶憑證、Alchemy Pay加密貨幣卡號碼和安全功能（包括CVV和PIN，如果有的話）。客戶應對因未能適當保護Alchemy Pay加密貨幣卡而導致的充值遺失或被盜負責，應盡快報告遺失或被竊。如果客戶或其他人允許其他人以任何其他目的使用加密貨幣卡，客戶將對此類使用負責，並可能需要對Alchemy Pay和服務提供者因此類使用而支付的所有金額或費用進行償還。客戶明白，其有責任在加密貨幣卡上監控任何可疑或未經授權的活動。客戶明白，根據適用法律的規定，它對未經授權使用Alchemy Pay加密貨幣卡的責任承擔到最大程度。',
    paragraphTitle6: '6. 卡片取消流程：',
    paragraphInfo6_1: '在停用卡片時從卡片余額中扣除1美元',
    paragraphInfo6_2: '用戶發起卡片取消請求時，系統會檢查賬戶中是否有余額。如果余額等於或大於10美元，則進行卡片取消退款流程。',
    paragraphInfo6_3: '如果賬戶中沒有余額，用戶將收到提示，確認銷毀加密貨幣卡。',
    paragraphInfo6_4: '無月費。',
    paragraphInfo6_5: '如果賬戶中的余額低於10美元，用戶將收到提示，通知他們余額不足以退款，然後要求確認取消。',
    paragraphInfo6_6: '在取消退款流程中，退款頁面將複製兌換頁面，提取金額將是固定的。',
  },

  // privacyPolicy 页面
  privacyPolicy: {
    title: '隱私政策',
    time: '最新更新日期：2022年4月13日',
    paragraphTitle1: 'Alchemy Pay全球隱私政策',
    paragraphInfo1:
      'Alchemy Pay（在“我們的實體和與您的關係”下有定義）致力於保護我們的網站訪問者和合作夥伴的隱私。本隱私政策描述了您在訪問我們的服務時我們如何處理您的個人資料，這些服務包括我們位於alchemypay.org等網站的內容，以及我們擁有或運營的任何其他網站、頁面、功能或內容（統稱為“網站”），或者任何Alchemy Pay應用程式設計發展介面或依賴於此類API的協力廠商應用程式，以及相關服務（以下統稱為“服務”）。',
    paragraphTitle2: '聯繫我們',
    paragraphInfo2_1: '如果您對本隱私政策有任何問題，您可以通過以下方式與我們聯繫：',
    paragraphInfo2_2: '通過電子郵件：',
    paragraphInfo2_4: '通過訪問我們網站上的此頁面：',
    paragraphTitle3: '1. 我們的實體',
    paragraphInfo3_1: 'Alchemy Pay通過Alchemy GPS Europe UAB（以下簡稱“Alchemy Pay”、“我們”、“我們的”）提供服務以滿足我們的客戶需求。',
    paragraphInfo3_2: 'Alchemy Pay可能與其它實體共用您的個人資料，並根據本隱私政策使用該資料。',
    paragraphInfo3_3: '地址：Laisvés pr. 60, LT-05120 Vilnius, Lithuania',
    paragraphInfo3_4: '編號：305972625',
    paragraphTitle4: '2. 收集和使用您的個人資料',
    paragraphTitle4_1: '2.1 收集的資料類型',
    paragraphTitle4_2: '2.1.1 個人資料',
    paragraphInfo4:
      '個人資料是指與能夠從該資料中識別出的生活個體有關的資料，或與Alchemy Pay（或其代表或服務提供者）擁有或可能擁有的其他資訊結合使用，可以從該資料中識別出該個體，除了事實資訊外，還包括關於個人的任何意見表達，以及Alchemy Pay或任何其他人對個人的意圖的任何指示。個人資料的定義取決於適用於您所在地的相關法律。',
    paragraphTitle5: '2.1.2 使用資料',
    paragraphInfo5_1: '使用服務時，有關資料會被自動收集。',
    paragraphInfo5_2: '相關資料可能包括諸如您設備的互聯網協定位址（例如IP位址）、流覽器類型、流覽器版本、您訪問的我們服務的頁面、存取時間和日期、在這些頁面上花費的時間、唯一設備識別字和其他診斷資料。',
    paragraphInfo5_3: '當您通過移動設備訪問服務時，我們可能會自動收集某些資訊，包括但不限於您使用的移動設備類型、您的移動設備唯一ID、您移動設備的IP位址、您的移動作業系統、您使用的移動互聯網流覽器類型、唯一設備識別號和其他診斷資料。',
    paragraphInfo5_4: '當您訪問我們的服務或通過移動設備訪問服務時，我們也可能收集您的流覽器在訪問服務時發送的資訊。',
    paragraphTitle6: '2.1.3 協力廠商數據',
    paragraphInfo6: '這包括Alchemy Pay從協力廠商來源獲取的有關您的資訊。我們從協力廠商接收您的個人資料的主要類型是：',
    paragraphInfo6_1: '公共資料庫、信用局和身份驗證合作夥伴，以依法驗證您的身份。身份驗證合作夥伴，如',
    paragraphInfo6_2: '，使用政府記錄和關於您的公開可用資訊結合使用，以驗證您的身份。此類資訊可能包括您的姓名、地址、職務、公共就業資料、信用歷史、公共機構維護的制裁名單上的狀態以及其他相關資料。',
    paragraphInfo6_3: '區塊鏈資料，以確保使用我們服務的各方未參與非法或禁止活動，並為研究和開發目的分析交易趨勢。',
    paragraphInfo6_4: '市場行銷合作夥伴和經銷商，以便更好地瞭解哪些服務可能對您感興趣。',
    paragraphInfo6_5: '您的金融服務提供者。例如，如果您從銀行帳戶向我們發送資金，您的銀行將向我們提供有關您的身份的資訊，以及關於您的帳戶的資訊，以便完成交易。',
    paragraphTitle7: '2.1.4 跟蹤技術和Cookie',
    paragraphInfo7_1: 'Alchemy Pay使用Cookie和類似的跟蹤技術來跟蹤我們服務的活動並存儲某些資訊。我們使用的跟蹤技術包括信標、標籤和腳本，以收集和跟蹤資訊，並改進和分析我們的服務。我們使用的技術可能包括：',
    paragraphInfo7_2: 'Cookie或流覽器Cookie。Cookie是放置在您的設備上的小檔。您可以指示您的流覽器拒絕所有Cookie，或在發送Cookie時指示。然而，如果您不接受Cookie，您可能無法使用我們服務的某些部分。除非您已調整了流覽器設置以拒絕Cookie，否則我們的服務可能會使用Cookie。',
    paragraphInfo7_3: 'Flash Cookie。我們服務的某些功能可能會使用本機存放區的物件（或Flash Cookie）來收集和存儲有關您的偏好或您在我們服務上的活動的資訊。Flash Cookie不受與流覽器Cookie相同的流覽器設置的管理。有關如何刪除Flash Cookie的更多資訊，請閱讀“在哪裡可以更改禁用或刪除本地共用物件的設置？”',
    paragraphInfo7_4: 'Web Beacons。我們服務的某些部分和我們的電子郵件可能包含稱為網路信標（也稱為清晰的gif、圖元標籤和單圖元gif）的小型電子檔，允許我們例如計算訪問這些頁面或打開電子郵件的使用者數，以及其他相關網站統計資訊（例如，記錄特定部分的受歡迎程度並驗證系統和伺服器的完整性）。',
    paragraphTitle8: '2.2 使用您的個人資料',
    paragraphTitle8_1: '2.2.1 我們如何使用您的個人資料',
    paragraphInfo8: 'Alchemy Pay可能以以下方式和目的使用您的個人資料：',
    paragraphInfo8_1: '提供和維護我們的服務，包括監控我們服務的使用情況。',
    paragraphInfo8_2: '為了維護法律和法規的合規性，我們需要處理您的個人資料以符合反洗錢和安全法律的規定。我們還會處理您的個人資料，以説明檢測、防止和減輕我們服務的濫用和欺詐行為，以及保護您免受帳戶受損或資金損失。',
    paragraphInfo8_3: '履行合同，為了執行您已購買的產品、商品或服務的購買合同的發展、合規和履行，或者與我們通過服務達成的任何其他合同。',
    paragraphInfo8_4: '通過電子郵件、電話、短信或其他等效的電子通信方式聯繫您，如與行政或與帳戶相關的資訊、安全問題或其他與交易相關的資訊的服務更新。這些通信是重要的，以分享可能影響您使用我們服務方式的發展。您不能選擇不接收關鍵的服務通信。',
    paragraphInfo8_5: '根據您的偏好和適用法律提供通信和客戶服務，我們可能向您發送行銷通信，以通知您有關事件，提供定向行銷，並共用促銷優惠。如果您是新的客戶或合作夥伴，我們將僅在您同意此類溝通的情況下，通過電子方式與您聯繫，進行行銷目的。如果您不希望我們發送行銷通信，請通過電子郵件提交請求。',
    paragraphInfo8_6: '當您聯繫我們解決任何問題、爭議或故障時，我們也會處理您的個人資訊。如果不處理您的個人資訊以達到此類目的，我們無法回應您的請求，確保您對服務的不間斷使用。',
    paragraphInfo8_7: '業務轉移，我們可能會使用您的資料來評估或進行合併、出售、重組、重組、解散或其他資產的出售或轉移，無論是作為持續經營的企業，還是作為破產、清算或類似程式的一部分，在這些過程中，我們對我們關於我們服務使用者的個人資料進行轉移。',
    paragraphInfo8_8: '其他目的：我們可能會出於其他目的使用您的資料，例如資料分析、識別使用趨勢、確定我們促銷活動的有效性，以及評估和改進我們的服務、產品、行銷和您的體驗。',
    paragraphTitle9: '2.2.2 將您的個人資料披露給協力廠商',
    paragraphInfo9: 'Alchemy Pay可能在以下情況下與他人共享您的個人資料：',
    paragraphInfo9_1: '與服務提供者共用：我們可能會與服務提供者共用您的個人資料，以監控和分析我們的服務的使用情況，與您聯繫。',
    paragraphInfo9_2:
      '與附屬公司共用：我們可能會與附屬公司共用您的資料，屆時我們將要求這些附屬公司遵守本隱私政策。附屬公司包括我們的母公司以及我們控制或與我們共同控制的任何其他子公司、合資夥伴或其他公司。我們的合同要求這些服務提供者只能在與他們為我們提供的服務相關的情況下使用您的資料，並禁止他們與任何其他人分享您的資料。',
    paragraphInfo9_3: '與商業夥伴共用：我們可能會與商業夥伴共用您的資料，以向您提供特定的產品、服務或促銷活動。這包括我們合作處理您授權的支付的金融機構。',
    paragraphInfo9_4:
      '與其他用戶共用：當您分享個人資料或以其他方式在公共區域與其他使用者互動時，這些資訊可能被所有使用者查看，並可能在外部公開分發。如果您與其他用戶互動，協力廠商社交媒體服務上的連絡人可能會看到您的姓名、個人資料、圖片和您的活動描述。同樣，其他用戶將能夠查看您的活動描述，與您溝通並查看您的個人資料。',
    paragraphInfo9_5: '業務轉移：如果我們涉及合併、收購或資產出售，您的個人資料可能會被轉移。在您的個人資料轉移並受到不同隱私政策約束之前，我們會提前通知您。',
    paragraphInfo9_6: '執法：在特定情況下，我們可能會根據法律要求披露您的個人資料，或者對公共當局的有效請求作出回應（例如，法院或政府機構）。',
    paragraphInfo9_7: '其他法律要求：我們可能會在善意的信念下披露您的個人資料，認為此類行動對於：',
    paragraphInfo9_8: '遵守法律義務',
    paragraphInfo9_9: '保護和維護我們的權利或財產',
    paragraphInfo9_10: '防止或調查與服務相關的潛在不當行為',
    paragraphInfo9_11: '保護服務使用者或公眾的個人安全',
    paragraphInfo9_12: '保護免受法律責任',
    paragraphInfo9_13: '在您的同意下，我們可能會出於任何其他目的披露您的個人資料。',
    paragraphTitle10: '3. 轉移您的個人數據',
    paragraphInfo10_1: '您的個人數據在Alchemy Pay的運營辦公室以及涉及處理的其他地方進行處理。這意味著這些信息可能會被轉移到您所在的州、省、國家或其他政府管轄區之外的計算機上，那些地方的數據保護法律可能與您的管轄區不同。',
    paragraphInfo10_2: '您對本隱私政策的同意以及您提交此類信息代表您同意該轉移。',
    paragraphInfo10_3: 'Alchemy Pay將採取一切合理必要的措施，以確保您的數據得到安全處理，並符合本隱私政策的規定，不會將您的個人數據轉移到沒有足夠控制措施的組織或國家，包括您的數據和其他個人信息的安全控制。',
    paragraphTitle11: '4. 保留您的個人數據',
    paragraphInfo11_1: 'Alchemy Pay僅會在本隱私政策所述的目的下保留您的個人數據。我們將保留和使用您的個人數據，以滿足我們的法律義務（例如，如果我們需要保留您的數據以符合適用法律的規定）、解決爭議，並執行我們的法律協議和政策。',
    paragraphInfo11_2: '我們還會為內部分析目的保留使用數據。使用數據通常保留的時間較短，除非該數據用於加強安全性或改進我們的服務的功能，或者我們有法律義務將這些數據保留更長時間。',
    paragraphTitle12: '5. 您的個人數據安全',
    paragraphInfo12_1: '您的個人數據的安全對我們至關重要，但請記住，互聯網傳輸或電子存儲的方法並不是100%安全的。儘管我們努力採用商業上可接受的手段保護您的個人數據，但我們無法保證其絕對安全。',
    paragraphInfo12_2: 'Alchemy Pay採取合理的措施來保護我們的信息和信息系統。根據相關信息的敏感性，客戶文件會受到保護措施的保護。我們在計算機系統上採取了合理的控制措施（例如限制訪問）。對於收集、處理或存儲個人信息的區域，物理訪問僅限於經授權的員工。',
    paragraphInfo12_3: '我們可能會在全球範圍內的任何地方存儲和處理您的全部或部分個人數據和交易信息，包括某些付款信息，例如加密的銀行帳號和/或路由號碼，這些地方是我們的設施或服務提供商所在的地方。我們通過符合適用法律和法規的物理、電子和程序性保障措施來保護您的個人信息。',
    paragraphInfo12_4: '作為雇佣條件，Alchemy Pay的員工必須遵守所有適用的法律法規，包括數據保護法。對敏感個人信息的訪問僅限於需要用於執行其職責的員工。Alchemy Pay員工未經授權不得使用或披露機密客戶信息，否則將受到紀律處分。',
    paragraphInfo12_5: '當您聯系Alchemy Pay的員工查詢您的文件時，可能會要求您提供一些個人細節。這種類型的保護措施旨在確保只有您或經您授權的人才能訪問您的文件。您在保護自己的個人信息方面也扮演著重要角色；不要向任何第三方透露個人數據，並在您發現任何未經授權訪問或使用您的賬戶時立即通知我們。',
    paragraphTitle13: '6. 兒童的個人數據',
    paragraphInfo13_1:
      'Alchemy Pay不會故意要求收集任何18歲以下的個人數據。如果懷疑提交個人信息的用戶年齡不滿18歲，Alchemy Pay將要求該用戶關閉其賬戶，並且不允許該用戶繼續使用我們的服務。我們還將採取措施 盡快刪除數據。如果您知道有任何18歲以下的個體使用我們的服務，請通知我們，以便我們採取措施防止他們訪問我們的服務。',
    paragraphTitle14: '7. 跨境轉移',
    paragraphInfo14_1: 'Alchemy Pay是一家在亞洲、歐盟、英國和美國等地區和國家運營的國際業務。這意味著我們可能會將數據轉移到您所在的國家之外的地方。當我們將您的個人信息轉移到另一個國家時，我們將確保任何個人信息的轉移都符合適用的數據保護法律。',
    paragraphTitle15: '8. 您的隱私權',
    paragraphInfo15_1: '根據您所居住的適用法律，您可能有權主張某些與您的個人數據有關的權利，這些權利包括：',
    paragraphInfo15_2: '獲取有關處理您的個人數據的信息，以及存取我們保存有關您的個人數據；',
    paragraphInfo15_3: '隨時撤回您對處理您的個人數據的同意。然而，請注意，如果我們有另一個合法原因來處理您的個人數據，我們可能仍有權處理您的個人數據。例如，我們可能需要保留個人信息以遵守法律義務。',
    paragraphInfo15_4: '在某些情況下，有權以結構化、通用和可讀的機器格式接收某些個人數據，並/或要求我們將這些數據傳輸給技術上可行的第三方。請注意，此權利僅適用於您直接向Alchemy Pay提供的個人信息；',
    paragraphInfo15_5: '在個人信息不準確或不完整的情況下，有權要求我們更正您的個人數據；',
    paragraphInfo15_6: '在某些情況下，有權要求我們在一定情況下刪除您的個人信息。請注意，可能有情況要求我們刪除您的個人數據，但我們在法律上有權保留；',
    paragraphInfo15_7: '在某些情況下，有權反對或要求我們限制我們處理您的個人數據。可能有情況要求您反對或要求我們限制處理您的個人數據，但我們在法律上有權拒絕該請求；',
    paragraphInfo15_8: '如果您認為我們侵犯了您的任何權利，有權向相關的數據保護監管機構投訴；',
    paragraphInfo15_9: '您可以通過電子郵件與我們聯系，行使您的權利，電子郵件地址為',
    paragraphInfo15_10: '。有關您的權利的更多信息，您可以聯繫您所在管轄區的監管數據保護機構。',
    paragraphTitle16: '9. 鏈接到其他網站',
    paragraphInfo16_1: '我們的服務可能包含鏈接到Alchemy Pay未經營的其他網站。如果您點擊第三方鏈接，您將被引導至該第三方的網站。我們強烈建議您查看您訪問的每個網站的隱私政策。',
    paragraphInfo16_2: 'Alchemy Pay無法控制並且不承擔任何第三方網站或服務的內容、隱私政策或做法的責任。',
    paragraphTitle17: '10. 本隱私政策的更改',
    paragraphInfo17_1: 'Alchemy Pay可能會不時更新我們的隱私政策。我們將通過在此頁面上發布新的隱私政策來通知您任何更改。',
    paragraphInfo17_2: '在更改生效之前，我們將通過電子郵件和/或在我們的服務上突出的通知來通知您，並在本隱私政策頂部更新“最近更新”日期。',
    paragraphInfo17_3: '建議您定期查看本隱私政策，以了解任何更改。本隱私政策的更改在發布在此頁面時生效。',
  },

  privacyPolicy1: {
    lastUpdated: '最後更新日期：2024年3月7日',
    headerText1_1: 'Bitstore Europe UAB（及其關聯公司和子公司）（統稱為“',

    headerText1_2: 'Bitstore',
    headerText1_3: '”， “',
    headerText1_4: '我們',
    headerText1_5: '”， “',
    headerText1_6: '我們',
    headerText1_7: '” 或 “',
    headerText1_8: '我們的',
    headerText1_9: '”）致力於保護我們網站訪問者和客戶的隱私。本隱私政策描述了當您訪問我們的服務時，我們如何處理您的個人數據，包括我們在 Bitstore 網站上的內容、我們擁有或運營的任何其他網站、頁面、功能或內容，或任何依賴此類 API 的 Bitstore API 或第三方應用程序（統稱為“',
    headerText1_10: '網站',
    headerText1_11: '”），以及相關服務（統稱為“',
    headerText1_12: '服務',
    headerText1_13: '”）。',

    title_1: '1. 收集和使用您的個人資料',
    title_1_1: '1.1 收集的資料類型',
    title_1_2: 'i. 個人資料',
    title_1_3: 'ii. 使用數據',
    title_1_4: 'iii. 來自第三方的數據',
    title_1_5: 'iv. 跟踪技術和Cookies',
    title_1_6: '1.2 使用您的個人資料',
    title_1_7: 'i. 我們如何使用您的個人資料',
    title_1_8: 'ii. 向第三方披露您的個人資料',
    paragraph1:
      '個人資料是指與一個活著的個人有關的任何數據，從這些數據，或者從這些數據和其他在Bitstore（或其代表或服務提供商）持有或可能獲得的信息中，可以識別出這個人。除了事實信息外，它還包括對個人的任何意見表達，以及Bitstore或任何其他人對個人的任何意圖表示。個人資料的定義取決於適用於您所在位置的相關法律。',
    paragraph1_2: '使用數據是在使用服務時自動收集的。',
    paragraph1_3: '使用數據可能包括例如您的設備的互聯網協議地址（例如IP地址）、瀏覽器類型、瀏覽器版本、您訪問我們服務的頁面、您的訪問時間和日期、您在那些頁面上花費的時間、唯一設備標識符和其他診斷數據。',
    paragraph1_4: '當您通過移動設備訪問服務時，我們可能會自動收集某些信息，包括但不限於您使用的移動設備類型、您的移動設備唯一ID、您的移動設備IP地址、您的移動操作系統、您使用的移動互聯網瀏覽器類型、唯一設備標識符和其他診斷數據。',
    paragraph1_5: '我們還可能會收集您的瀏覽器在每次訪問我們的服務或通過移動設備訪問服務時發送的信息。',
    paragraph1_6: '這包括Bitstore可能從第三方來源獲得的關於您的信息。我們從第三方接收您的個人數據的主要類型是：',
    paragraph1_7: '公共數據庫、信用局和身份驗證合作夥伴，以根據適用法律驗證您的身份。身份驗證合作夥伴可能會使用政府記錄和公開可用的關於您的信息組合來驗證您的身份。這些信息可能包括您的姓名、地址、工作角色、公開的工作資料、信用歷史、公共機構維護的任何制裁名單上的狀態和其他相關數據。',
    paragraph1_8: '區塊鏈數據，以確保使用我們服務的各方未參與非法或禁止的活動，並分析交易趨勢以進行研究和開發。',
    paragraph1_9: '營銷合作夥伴和經銷商，以便我們更好地了解哪些服務可能對您感興趣。',
    paragraph1_10: '您的金融服務提供商。例如，如果您從您的銀行賬戶向我們發送資金，您的銀行將向我們提供識別信息以及關於您的賬戶的信息，以完成交易。',
    paragraph1_11: 'Bitstore使用Cookies和類似的跟踪技術來跟踪我們服務的活動並存儲某些信息。使用的跟踪技術包括信標、標籤和腳本，以收集和跟踪信息並改進和分析我們的服務。我們使用的技術可能包括：',
    paragraph1_12: 'Cookies或瀏覽器Cookies。Cookie是一個放置在您設備上的小文件。您可以指示您的瀏覽器拒絕所有Cookies或指示何時發送Cookie。然而，如果您不接受Cookies，您可能無法使用我們服務的部分或全部功能。除非您已調整瀏覽器設置以拒絕Cookies，否則我們的服務可能會使用Cookies。',
    paragraph1_13: '網頁信標。我們的服務的某些部分和我們的電子郵件可能包含稱為網頁信標的小電子文件（也稱為清晰GIF、像素標籤和單像素GIF），允許我們例如計算訪問這些頁面的用戶數量或打開電子郵件的用戶數量，並進行其他相關的網站統計（例如記錄某個部分的受歡迎程度並驗證系統和服務器的完整性）。',
    paragraph1_14: 'Bitstore可能以以下方式和目的使用您的個人資料：',
    paragraph1_15: '提供和維護我們的服務，包括監控我們服務的使用情況。',
    paragraph1_16: '為了維護法律和法規的合規性，我們需要處理您的個人資料，以便遵守反洗錢和安全法規。我們還處理您的個人資料，以幫助檢測、防止和減少欺詐和濫用我們的服務，並保護您免於賬戶被盜用或資金損失。',
    paragraph1_17: '履行合同，開發、遵守和履行您通過我們的服務購買的產品、物品或服務的購買合同或任何其他合同。',
    paragraph1_18: '通過電子郵件、電話、短信或其他等效的電子通信方式（如服務更新、管理或賬戶相關信息、安全問題或其他交易相關信息）與您聯繫。這些通信對於分享可能影響您使用我們服務的發展非常重要。您不能選擇退出接收關鍵服務通信。',
    paragraph1_19: '根據您的偏好和適用法律提供通信和客戶服務，我們可能會向您發送營銷通信，通知您有關活動，提供定向營銷和分享促銷優惠。如果您是新客戶或合作夥伴，我們僅在您同意此類通信的情況下，通過電子方式與您聯繫進行營銷。如果您不希望我們向您發送營銷通信，請通過電子郵件提交請求。',
    paragraph1_20: '當您聯繫我們解決任何問題、爭議或排除故障時，我們也會處理您的個人信息。如果不處理您的個人信息，我們無法回應您的請求並確保您不間斷地使用我們的服務。',
    paragraph1_21: '在業務轉讓中（如適用），我們可能會使用您的數據來評估或進行合併、剝離、重組、重組、解散或其他出售或轉讓我們的一些或全部資產，不論是作為經營中的企業還是作為破產、清算或類似程序的一部分，我們持有的有關我們服務用戶的個人數據將作為轉讓的資產之一。',
    paragraph1_22: '為其他目的：我們可能會將您的數據用於其他目的，例如數據分析、識別使用趨勢、確定我們促銷活動的有效性以及評估和改進我們的服務、產品、服務、營銷和您的體驗。',
    paragraph1_23: 'Bitstore可能在以下情況下分享您的個人數據：',
    paragraph1_24: '與服務提供商：我們可能會與服務提供商分享您的個人數據，以監控和分析我們服務的使用情況，與您聯繫。',
    paragraph1_25:
      '與關聯公司：我們可能會與我們的關聯公司分享您的數據，在這種情況下，我們將要求這些關聯公司遵守本隱私政策。關聯公司包括我們的母公司和我們控制或與我們共同控制的任何其他子公司、合資企業合作夥伴或其他公司。我們的合同要求這些服務提供商僅將您的數據用於與我們執行的服務相關的用途，並禁止他們與任何其他人分享您的數據。',
    paragraph1_26: '與業務合作夥伴：我們可能會與我們的業務合作夥伴分享您的數據，以向您提供某些產品、服務或促銷活動。這包括我們合作處理您授權付款的金融機構。',
    paragraph1_27:
      '與其他用戶：當您與其他用戶在公共區域共享個人數據或以其他方式互動時，這些信息可能會被所有用戶查看並可能在公共區域分發。如果您與其他用戶互動，您的第三方社交媒體服務上的聯繫人可能會看到您的姓名、個人資料圖片和活動描述。同樣，其他用戶將能夠查看您的活動描述，與您通信並查看您的個人資料。',
    paragraph1_28: '業務轉讓：如果我們參與合併、收購或資產出售，您的個人數據可能會被轉讓。我們將在您的個人數據被轉讓並受另一隱私政策約束之前提供通知。',
    paragraph1_29: '執法：在某些情況下，如果法律要求或公共機構（如法院或政府機構）的有效請求，我們可能需要披露您的個人數據。',
    paragraph1_30: '其他法律要求：我們可能會在真誠相信這種行動是必要的情況下披露您的個人數據：',
    paragraph1_31: 'a) 遵守法律義務',
    paragraph1_32: 'b) 保護和捍衛我們的權利或財產',
    paragraph1_33: 'c) 防止或調查與服務有關的可能的錯誤行為',
    paragraph1_34: 'd) 保護服務用戶或網站訪問者的個人安全',
    paragraph1_35: 'e) 防止法律責任',
    paragraph1_36: '經您的同意：我們可能在您事先同意的情況下為任何其他目的披露您的個人數據。',

    title2: '2. 您的個人資料轉移',
    paragraph2_1: '您的個人資料在Bitstore的運營辦公室以及處理相關各方所在的其他地方進行處理。這意味著這些信息可能會轉移到 - 並保存在 - 位於您所在的州、省、國家或其他政府管轄範圍之外的計算機上，那裡的數據保護法律可能與您所在的司法管轄區不同。',
    paragraph2_2: '您同意本隱私政策並提交此類信息即表示您同意此類轉移。',
    paragraph2_3: 'Bitstore將採取一切合理必要的步驟，以確保您的數據安全並根據本隱私政策進行處理，除非有適當的控制措施，包括您的數據和其他個人信息的安全性，否則不會將您的個人數據轉移到任何組織或國家。',

    title3: '3. 您的個人資料的保存',
    paragraph3_1: 'Bitstore僅在本隱私政策中所述目的必要期間保留您的個人資料。我們將在法律義務範圍內保留和使用您的個人資料（例如，如果我們需要保留您的數據以遵守適用法律），解決爭議並執行我們的法律協議和政策。',
    paragraph3_2: '我們還將保留用戶數據以供內部分析用途。用戶數據通常會保留較短的時間，除非這些數據用於加強安全性或改進我們服務的功能，或我們依法有義務保留這些數據較長的時間。',

    title4: '4. 您的個人資料的安全性',
    paragraph4_1: '您的個人資料的安全對我們很重要，但請記住，互聯網上的傳輸方式或電子存儲方式並非100%安全。儘管我們努力使用商業上可接受的方法來保護您的個人資料，但我們無法保證其絕對安全性。',
    paragraph4_2: 'Bitstore實施並維護合理的措施來保護我們的信息和信息系統。根據相關信息的敏感性保護客戶文件。對我們的計算機系統進行合理的控制（如限制訪問）。對收集、處理或存儲個人信息的區域的物理訪問僅限於授權員工。',
    paragraph4_3: '我們可能在我們的設施或服務提供商所在地的任何地方存儲和處理您的一部分或全部個人資料和交易信息，包括某些支付信息，如您的加密銀行賬戶和/或路由號。我們通過保持符合適用法律和法規的物理、電子和程序保障措施來保護您的個人信息。',
    paragraph4_4: '作為雇用條件，Bitstore的員工需要遵守所有適用法律和法規，包括與數據保護法相關的法律。對敏感個人信息的訪問僅限於需要履行其職責的員工。Bitstore員工未經授權使用或披露機密客戶信息是被禁止的，並可能導致紀律處分。',
    paragraph4_5: '當您聯繫Bitstore員工有關您的文件時，可能會被要求提供一些個人詳細信息。這種保障措施旨在確保只有您或您授權的人才能訪問您的文件。您在保護自己的個人信息方面也起著至關重要的作用；請勿向任何第三方透露個人資料，並在發現任何未經授權訪問或使用您的帳戶時立即通知我們。',

    title5: '5. 兒童的個人資料',
    paragraph5_1:
      'Bitstore不會故意要求收集任何18歲以下或65歲以上的人的個人資料。如果提交個人信息的用戶被懷疑年齡低於18歲或高於65歲，Bitstore將要求用戶關閉其帳戶，並且不允許用戶繼續使用我們的服務。我們還將採取措施盡快刪除數據。如果您知道有任何18歲以下或65歲以上的個人使用我們的服務，請通知我們，以便我們採取措施防止其訪問我們的服務。',

    title6: '6. 跨境轉移',
    paragraph6_1: 'Bitstore是一家在亞洲和歐盟等地區和國家運營的國際業務，這意味著我們可能會轉移您的個人信息到您的國家之外的地點。當我們將您的個人信息轉移到另一個國家時，我們將確保任何個人信息的轉移都符合適用的數據保護法律。',

    title7: '7. 您的隱私權',
    paragraph7_1: '根據您居住國家/地區的適用法律，您可能有權主張與您的個人數據相關的某些權利。這些權利包括：',
    paragraph7_2: '獲取有關我們處理您個人數據的信息並訪問我們持有的關於您的個人數據的權利；',
    paragraph7_3: '隨時撤回您對處理您個人數據的同意的權利。但請注意，如果我們有其他合法理由處理您的個人數據，我們仍然有權這樣做。例如，我們可能需要保留個人信息以遵守法律義務；',
    paragraph7_4: '在某些情況下，獲得一些個人數據的權利，這些數據以結構化、常用和機器可讀格式提供，和/或請求我們在技術可行的情況下將這些數據傳輸給第三方。請注意，這項權利僅適用於您直接向Bitstore提供的個人信息；',
    paragraph7_5: '在您的個人數據不準確或不完整的情況下，請求我們更正的權利；',
    paragraph7_6: '在某些情況下請求我們刪除您的個人信息的權利。請注意，可能會有某些情況，即使您要求我們刪除您的個人數據，但我們在法律上有權保留它；',
    paragraph7_7: '在某些情況下，反對或請求我們限制處理您的個人數據的權利。可能會有某些情況，即使您反對或請求我們限制處理您的個人數據，但我們在法律上有權拒絕該請求；',
    paragraph7_8: '如果您認為我們侵犯了您的任何權利，有權向相關的數據保護監管機構投訴的權利；',

    title8: '8. 其他網站的鏈接',
    paragraph8_1: '我們的服務可能包含指向其他非Bitstore運營的網站的鏈接。如果您點擊第三方鏈接，將被導向該第三方的網站。我們強烈建議您查看每個您訪問的網站的隱私政策。',
    paragraph8_2: 'Bitstore對任何第三方網站或服務的內容、隱私政策或實踐不承擔任何責任。您同意不將因點擊此類第三方鏈接或使用此類第三方網站或服務而產生的任何損失歸咎於我們。',

    title9: '9. 本隱私政策的變更',
    paragraph9_1: 'Bitstore可能會不時更新我們的隱私政策。我們將通過在網站上發布新隱私政策通知您任何變更。',
    paragraph9_2: '我們可能會通過電子郵件和/或網站上的顯著通知，並在變更生效前更新本隱私政策頂部的“最後更新”日期來通知您。',
    paragraph9_3: '我們建議您定期查看本隱私政策的任何變更。變更在發布到本頁面時生效。',
  },

  // recharge 充值页面
  recharge: {
    title: '至卡片',
    title1: '充值',
    title2: '逆轉負餘額',
    subtitle_wallt: '充值金額',
    bubble: '您要充值到您的卡片餘額的金額',
    You_need_to_pay: '您需要支付',
    You_will_pay: '您將支付',
    from: '從',
    Recharge_fee: '充值手續費',
    btn_text: '確認',
    SelectCrypto: '選擇加密貨幣',
    errTip1: '您已超過本月的最大充值限額。',
    errTip2: '最低充值餘額為',
    pay: '支付',
    will_recharge: '您將充值',

    will_receive: '您將收到',
    deductionFee: '待扣除的累積月費',
    systemErrTip: '銀行系統正在維護中，請稍後再試。',
    excessErrTip: '單次充值金額超過最大限額。',
  },

  // rechargeDetails 充值待支付页
  rechargeDetails: {
    title: '卡片存款',
    Paymentamount: '支付金額',
    tip: '此金額不包括您進行交易時的網絡費用。例如，訂單金額為100 USDT，您選擇的網絡是Trc20。最終，如果您使用中心化交易所提款，您需要轉賬101 USDT。',
    RechargeAddress: '充值地址',
    payDepositTip1: '1. 請保持充值金額與訂單金額一致，否則會導致資金損失',
    payDepositTip2: '2. 平均到帳時間：5分鐘~10分鐘',
    payDepositTip3: '3. 此地址僅接受',
    payDepositTip4: '4. 請不要向此地址充值任何其他資產',
    countDownTip: '請在此時間內完成轉賬',
  },

  // rechargeError 充值失败页面
  rechargeError: {
    Recharge: '充值失敗',
    Payment_succeeded: '支付成功',
    Failed_reason: '失敗原因',
    Recharge_Failed_content: '您的實際存款金額低於我們的限制（5美元），請查看公告電子郵件並申請退款。',
    btn: '返回主頁',
  },

  // rechargePadding 充值等待页面
  rechargePadding: {
    Inprocessing: '處理中...',
    Payment_succeeded: '支付成功',
    Recharging_amount: '正在充值金額',
    tip: '加密虛擬卡已成功生成',
  },

  // rechargeTimeOut 充值超时页面
  rechargeTimeOut: {
    title: '充值超時',
    btn: '返回主頁',
  },

  // rechargeSuccess 充值成功页面
  rechargeSuccess: {
    Recharge: '充值成功！',
    Payment_succeeded: '支付成功',
    Recharge_completed: '充值已完成',
    Card_holder: '持卡人',
    Card_number: '卡號',
    Recharge_mount: '充值金額',
    Balance: '餘額',
    Recharge_date: '充值日期',
    btn_text2: '返回主頁',
  },

  // 透支删卡走充值流程
  delAndOverdraft: {
    btn1: '反轉負餘額並刪除卡片',
    title: '反轉負餘額',
    cancelSuccessful: '取消成功！',
    tip1: '成功反转负余额。',
    tip2: '虛擬卡已成功取消。',
    rechargeSuccess: '充值成功！',
    tip3: '充值成功',
    reverseAmount: '反转金额',
  },

  // withdraw 赎回页面
  withdraw: {
    title: '贖回',
    withdraw_tip: '卡片餘額必須至少為1美元',
    Withdraw_amount: '贖回金額',
    popoverText: '您想退還到您的私人錢包地址的金額',
    Receive_amount: '接收金額',
    Send_to: '錢包地址',
    address_required: '必須填寫地址',
    Invalid_address: '無效的地址',
    Network: '網絡',
    You_will_receive: '您將接收',
    from: '贖回',
    Network_fee: '網絡費用',
    btn: '確認',
    Select_Crypto: '選擇加密貨幣',
    errTip: '超出卡片可贖回餘額。',
    errTip1: '最低退款餘額為 ',
    errTipETH: '最低退款餘額為50美元。',
    withdraw_address_tip: '僅支援提現到個人錢包地址。',

    withdrawTipTitle1: '根據銀行監管要求，提現餘額需要間隔48小時，此期間內無法再次發起提現請求。',
    withdrawTipInfo1: '在發起提現請求時，請確保帳戶中至少還有1美元的餘額。',
    withdrawTipInfo2: '最低提現金額為3美元；如果餘額不足3美元，您可以在進行餘額提現之前進行儲值。',
    withdrawTipInfo3: '請勿使用已刪除的卡片進行交易，否則可能導致退款，進而導致帳戶被暫停使用。',
    withdrawTipTitle2: '刪除卡片時，為什麼部分餘額無法提現？',
    withdrawTipInfo4: '如果您的卡片包含月費，該費用在創建卡片時首先預留在卡片中，在30天後扣除。隨後的每筆月費會在72小時後鎖定。',
  },

  // withdrawPedding  赎回等待页面
  withdrawPedding: {
    title: '加密貨幣發送中...',
    Withdraw_confirmed: '贖回已確認',
    Withdraw_completed: '贖回已完成',
    Withdraw_amount: '贖回金額',
    Network: '網絡',
  },

  // withdrawError  赎回等待页面
  withdrawError: {
    Withdraw_failed: '贖回失敗',
    Withdraw_confirmed: '贖回已確認',
    Failed_reason: '失敗原因',
    tip: '退款失敗。您的錢包地址無效。請聯繫客戶服務或更換其他地址。',
    btn: '返回主頁',
  },

  // withdrawSuccessed 赎回成功页面
  withdrawSuccessed: {
    title: '贖回成功！',
    Withdraw_confirmed: '贖回已確認',
    Withdraw_completed: '贖回已完成',
    Withdraw_amount: '贖回金額',
    Network: '網絡',
    HxID: 'HxID',
    btn: '返回主頁',
  },

  // history 订单历史页面
  history: {
    title: '訂單歷史',
    title1: '消費歷史',
    Recharge: '充值',
    RechargeAmount: '充值金額',
    Refund: '退款',
    RefundAmount: '贖回金額',
    No_orders_yet: '暫無訂單',
    Recharge_succeeded: '充值成功',
    In_processing: '處理中',
    Recharge_failed: '充值失敗',
    Recharge_timeout: '充值超時',
    Refund_succeeded: '贖回成功',
    Refund_failed: '贖回失敗',
    Actual_amount: '實際金額',
    Network_fee: '網絡費用',
    Recharge_fee: '充值手續費',
    Order_number: '訂單號碼',
    Order_time: '訂單時間',
    cancelBtn: '取消',

    confirmBtn: '確認',
    tip: '選擇期間',
    to: '至',
    noMore: '沒有了~',

    smallFeeTip: '通知：',
    smallFee: '小額購買手續費',
    foreignFee: '跨境手續費',
    smallFeeTip1: '請注意，如果您的交易被拒絕，交易手續費仍然會被收取。',

    declineFee: '拒絕費用返還',
    returnSuccessfully: '退款成功',
    returnAmount: '退款金額',
    actualAmount: '實際金額',
    orderNumber: '訂單號碼',
    orderTime: '訂單時間',
  },

  kycHome: {
    title: '創建持卡人',
    creatVirCardTitle: '申請卡片',
    levelUpTitle: '升級',
  },

  // levelUp 卡升级页面
  levelUp: {
    title: '卡片升級',
    Card_Type: '卡片類型',
    Lite: '輕量版',
    Current: '當前',
    Standard: '標準版',
    btn: '升級',
    Apply_fee: '申請費用',
    limit_month: '每月充值限額',
    Consumption_fee: '消費費用',
    KYC: '實名認證',
    Verify_KYC: '實名認證驗證',
    No_KYC: '未實名認證',
    Recharge_fee: '充值手續費',
    Terms_of_validity: '有效期限',
    year: ' 年',
  },

  // levelUp 卡升级页面
  levelUpSuccess: {
    title: '升級成功！',
    Cardholder: '持卡人',
    Address: '地址',
    Balance: '餘額',
    Expired: '過期',
    btn: '返回主頁並開始使用',
    limitMonth1: '每月卡片限額',
  },

  // 个人信息
  PersonalInfo: {
    Email: '郵箱',
    KYC: '實名認證',
    No_KYC: '未實名認證',
    processing: '處理中',
    abnormalStatus: '異常狀態',
    Approved: '已批准',
    Language: '語言',
    Terms_of_Service: '服務條款',
    Privacy_Policy: '隱私政策',
    Safety_Validation: '安全驗證',
    Basic_Information: '基本資訊',
    Log_Out: '登出',
    Cancel: '取消',
    Confirm: '確認',
    verify: '驗證',
    approved: '已批准',
    inProcessing: '處理中',
    failed: '失敗',
  },

  // 退出登录弹窗
  logout: {
    msg: '您是否要登出？',
    Cancel: '取消',
    Confirm: '確認',
  },

  // Safety Validation 安全认证页面
  safetyValidation: {
    title: '安全驗證',
    Email_Verification: '郵箱驗證',
    Google_Authenticator: 'Google 身份驗證器',
    Activate: '啟用',
    Approved: '已批准',
  },

  // googleAuthenticator 谷歌认证页面
  googleAuthenticator: {
    title: 'Google 身份驗證器',
    tip: '請下載 Google 身份驗證器應用程序並掃描 QR 碼',
    DownloadAPP: '下載應用程序',
    btn: '繼續',
  },

  // downloadApp 下载app页面
  downloadApp: {
    title: '下載APP',
    IOS: 'IOS',
    Android: 'Android',
  },

  // googleCode 谷歌绑定验证码页面
  googleCode: {
    title: 'Google 身份驗證器',
    Email_code: '郵箱驗證碼',
    Google_code: 'Google 身份驗證器驗證碼',
    Send_code: '發送驗證碼',
    btn: '繼續',
    tip: '驗證碼已發送',
  },

  // 卡片信息
  card: {
    blance: '餘額',
    expiry: '到期：',
  },

  // 小卡片信息
  small_card: {
    blance: '餘額',
  },

  // 弹窗
  text_popup: {
    popup_confirm: '確認',
    popup_cancel: '取消',
  },

  // addEdit 修改卡地址页面
  addEdit: {
    title: '更新您的帳單地址',
    warn1: '1. 請填寫您的實際帳單地址，位於美國。',
    warn2: '2. 請注意，您只能在1個月內更改帳單地址一次。',
    tip: '您的帳單地址是什麼？',
    tip1: '請提供美國的帳單地址',
    Street_address: '街道地址',
    streetAddressPlaceholder: '2012 Habersham St',
    errorTips: '您的地址無效',
    City: '城市',
    CityPlaceholder: 'Savannah',
    errorTipsCity: '您的城市無效',
    State: '州',
    Zip_code: '郵編',
    Zip_code_placeholder: '郵編',
    Zip_code_Err: '您的郵編無效',
    Select_State: '選擇州',
    msg: '更新成功',
    btn: '確認',
  },

  copy: {
    tip: '已複製',
  },

  /******************************新添加 实体卡******************************/
  phyCardKYC: {
    btn1: '我來自EEA',
    info1: '支持身份證和護照',
    btn2: `我來自EEA以外的地方`,
    info2: '支持護照',
  },

  physicalForm: {
    phoneTitle: 'Create a card holder',
    title: '請輸入您的電話號碼',
    codePlaceholder: '輸入您的驗證碼',
    firstName: '名字',
    lastName: '姓氏',
    gender: '性別',
    male: '男',
    female: '女',
    birthday: '生日',
    nationality: '國籍',
    btn: '確認',
    serach: '搜索這裡...',
    phonePlaceholder: '輸入手機號碼',
  },

  phyCardState: {
    title: '創建持卡人',
    review: '審核已提交！',
    successful: '註冊成功！',
    failed: '註冊失敗！',

    reason1: '通常核實需要2個工作日完成，您可以隨時在個人資料 >',
    reason2: '“基本信息”',
    reason3: '中檢查您的進度。',

    resubmitBtn: '重新提交',
    backBtn: '回到主頁',
    resubmitTip: '是否重新提交審核？',
    cancelBtn: '取消',
    confirmBtn: '確認',
    errorReason1: '您未通過持卡人創建驗證。',
    errorReason2: '請先聯繫客服並重置 KYC。',
    errorReason3: '重置後，您可以重新提交您的身份驗證材料。點擊下方按鈕進行重新提交。',
    resubmitTip1: '請重新提交您的持卡人申請',
  },

  phyCardActive: {
    title: '啟用我的實體卡',
    firstName: '名字',
    lastName: '姓氏',
    tipInfo: '輸入您的卡號',
    btn: '確認',

    title1: '啟用您的卡片',
    title2: '序號範例',
    title3: '卡號範例',
    cardNumber: '卡號',
    serialNumber: '序號',
    placeholderTip: '請輸入七位數序號',
    enterCVV: '請輸入 CVV',
  },

  phyCardCreate: {
    title: '新增實體卡',
    introduce: {
      line1_1: '使用USDT和USDC儲值',
      line1_2: '使用加密穩定幣快速充值美元',
      line2_1: '全球范圍內任何地方都可消費',
      line2_2: '可在任何美元支付場景中使用，並可與Apple Pay綁定',
      line3_1: '提取現金資產',
      line3_2: '可以在200多個國家的自動提款機上提取您的數字資產現金',
      line4_1: '使用USDT、USDC、BTC和ETH進行充值',
      line4_2: '它可以在任何歐元支付情境中使用，並且可以綁定到 Apple Pay 上',
      line4_2_1: '它可以在任何歐元支付場景中使用',
    },
    step: {
      tip: '您離擁有實體卡只需幾個步驟',
      step1: '第一步',
      step2: '第二步',
      step3: '第三步',
      step4: '第四步',
      KYC: 'KYC',
      holder: '創建持卡人',
      activeCard: '訂購卡片或啟用您的卡片',
      done: '完成!',
    },
    btn1: '訂購實體卡片',
    btn2: '啟用我的卡片',
  },

  phyCardCreateForm: {
    title: '訂購卡片',
    btn: '確認',
    infoView_1: {
      title: '收件人',
      firstName: '名字',
      lastName: '姓氏',
      countryCode: '國家代碼',
    },
    infoView_2: {
      title: '送貨地址',
      title1: '聯繫電話',
      address: '地址',
      address_placeholder: '請輸入送貨地址',
      city: '城市',
      city_placeholder: '請輸入城市',
      country: '國家',
      country_placeholder: '請輸入國家',
      state: '州/省（選填）',
      state_placeholder: '州/省',
      zipCode: '郵遞區號',
      zipCode_placeholder: '郵遞區號',
      placeholder: '請輸入您的手機號碼',
      addressHouse: '房屋號或房間號',
    },
    serach: '在此搜索...',
  },

  phyCardApplyCard: {
    title: '卡片信息',
    title1: '申請卡片',
    btn: '支付',
    text_1: '申請費用',
    text_2: '每月限額',
    text_3: '月費',
    text_4: '運費',
    text_5: '充值費用',
    text_6: '交易費用',
    text_7: '收據信息',
    text_8: '持卡人',
    text_9: '電話號碼',
    text_10: '地址',
    text_11: '選擇您要支付的代幣',

    text_12: '優惠碼',
    text_13: '輸入您的優惠碼',

    text_14: '來自歐洲經濟區（EEA）：0%，',
    text_15: '來自歐洲經濟區以外：2%，最低€ 0.6',

    monthly_fee_tip: '月費包括月費和服務費。 每月將在當月的第30日UTC+2時區22:00扣除。',

    expireDate: '到期日期：',
    discount: '折扣',
    confirm: '確認',
    discountTip: '在活動期間使用特定代幣享受折扣',
  },

  phyCardSendingLogistics: {
    text_1: '我們正在處理您的訂單',
    text_2: '訂單詳情',
    text_3: '處理中...',
    text_4: '在途中',
    text_5: '已交付',
    text_6: '收到您的卡片了嗎？',
    text_7: '當您收到實體卡後，請點擊此處按鈕啟用全部功能',
    text_8: '等待申請結果',
    info: '郵寄實體卡片將完全由 ',
    info1: '負責',
    btn: '立即啟用',
  },

  logisticsDetails: {
    title: '物流詳情',
    title_2: '送貨地址',
    title_3: '快遞號',
    no_logistic_title: '目前沒有追蹤狀態，請耐心等待',
    no_logistic_title1: '您可以查看物流信息，並根據物流訂單號碼收取商品。',
  },

  activeSuccessed: {
    title1: '實體卡',
    title: '啟用成功！',
    time: '啟用時間',
    btn: '回到主頁並開始使用它',
    card_holder: '持卡人',
    card_number: '卡號',
    balance: '餘額',
  },

  langue: {
    title: '語言',
  },

  basicInfor: {
    title: '基本信息',
    verify: '驗證',
    processing: '處理中',
    failed: '失敗',
    approved: '已批准',
  },

  virPhyHome: {
    text: '在短短几分钟内获得加密卡，而不是几天。像使用Paypal、支付宝等支付方式一样花费加密货币。',
    cardBalance: '卡片餘額',
    add: '新增',
    hideCardTip: '隱藏所有已移除的卡片。',
  },

  virCard: {
    title: '虛擬卡',
    addTitle: '新增虛擬卡片',
    vir_title: '您可以使用加密卡片進行',
    subtitle_virtual_cards: '虛擬卡',
    common_title: '常見用途',
  },

  virCardInfo: {
    applyFee: '申請費',
    limitMonth: '卡限額/月',
    monthlyFee: '月費',

    KYC: '身份驗證',
    verifyKYC: '是',
    noKYC: '否',
    riskScenario1: '受限使用',

    rechargeFee: '充值費',
    transactionFee: '交易費',
    riskScenario: '受限使用',
    riskControlRules: '風險控制規則',

    monthlyCardFee: '月卡費',
    monthlyLimit: '每月限額',
    cardApplicationFee: '申請費',

    tip1: '0.15 美元（低于 10 美元的消费)',
    tip2: '非美元购买将收取0.8%的交易费用。',

    monthlyFeeTip1: '從用戶的卡片創建日期開始，每隔30天將扣除月費，扣款時間為當地時間該日的凌晨00:00。',
    monthlyFeeTip2: ' 將被鎖定在卡片餘額中，不能兌換或花費。',
    monthlyFeeTip2_1: '每個新月份 $',
    monthlyFeeTip3: '刪除卡片後，將停止對該虛擬卡片扣除的月費。',

    activeAt: '啟用於',
    activeAt1: 'UTC+8',

    tip: '下一次月費扣款日期:',
    tip1_1: '低於45美元：0.5美元+2％;',
    tip2_1: '超過45美元：2％;',
    tip3_1: '拒絕消費的費用為0.5美元',

    tip4: '0.15 美元（消費低於10美元）',
    tip5: '拒絕非美國消費的0.5美元手續費',
    tip6: '將收取0.8%的交易手續費（卡bin：556766 / 531847 / 558068）',
    tip7: '低於45美元：0.5美元+2%；45美元以上：2％（卡bin：553437）',

    tip8: '包含卡費75歐元和年費65歐元。',
    tip9: '包括卡片申請費60歐元和年費180歐元。',

    tip10: '不同代币的充值费用不同',
    tip11: '',
    messageErr: '系統正在維護中，付款暫時無法使用。',
  },

  riskTipInfo: {
    title1: '虛擬卡禁止綁定任何支付金融產品、加密貨幣和其他高風險平台。常見的禁止場景包括：',
    financialPayment: '金融支付',
    consumptionPlatform: '消費平台',
    riskPlatform: '風險平台',
  },

  phyCard: {
    title: '實體卡',
    addTitle: '新增實體卡片',
    cardType3: '實體卡',
    subtitle_physical_cards: '實體卡',
    phy_title: '您可以使用實體卡進行以下操作',
    physicalCardsFooter: '該卡由Paytend Europe UAB根據MasterCard International Inc.的許可發行。Paytend Europe UAB根據立陶宛銀行的規定獲得授權，進行2011年電子貨幣規定（Ref：900051）下的電子貨幣服務活動。',
    btn_p: '新增實體卡',
    info1: '歐洲以外地區',
    info2: '最低0.6歐元',
  },

  // 未登录页 实体卡 滚动组件
  noLogPhyCards: {
    title: '您可以使用實體卡進行以下操作',
    item1: '離線',
    info1: '離線滑動卡片',
    item2: '在線',
    info2: '在線購物',
    item3: 'ATM',
    info3: 'ATM提款',
  },

  noLogVirCards: {
    itemTitle7: 'WeChat',
    itemInfo7: 'WeChat Pay is fully open to bind overseas cards',
    itemTitle8: 'Alipay',
    itemInfo8: 'Alipay now supports binding overseas bank cards',
  },

  applyVir: {
    phoneTitle: '開始申請您的虛擬卡',
    chooseCard: '選擇一張卡片',
    countryRegion: '國家/地區',
    settlementCurrency: '貨幣',
    commonCases: '常見用途',
    tip: '請注意，支持狀態依賴於數據和測試，可能會因風險控制修改而更改',
    smallFee: '小額購買手續費：',
    foreignFee: '跨境手續費',
  },

  noVirCardHome: {
    virTitle: '虛擬卡',
    virIntro: '虛擬力，現實便利',
    virBtn: '申請一張新卡',
    phyTitle: '實體卡',
    phyIntro: '從加密到商業，盡在您的手中',
    phyBtn: '新增實體卡',
  },

  multipleCardPC: {
    noCard: '沒有卡片',
    mastercard: 'Mastercard',
    inProcessing: '處理中...',
    addCard: '新增卡片',
    myCards: '我的卡片',
    maxCard: '達到最大卡片數量',
    add: '新增',
  },

  phyCardFailureNotification: {
    title: '故障通知',
    info1: '您目前持有',
    info1_1: '3張實體卡',
    info1_2: '由',
    info1_3: 'Paytend',
    info1_4: '發行。',
    info2: '根據我們的規定，持卡人最多可以持有',
    info2_1: '3張實體卡。',
    info2_2: '如果您希望申請新卡，請聯繫我們的客戶服務部門停用您現有的任何一張實體卡。',
  },

  viewPIN: {
    title: '查看PIN碼',
    PIN: 'PIN碼',
    tip1: '您可以在POS機和ATM上使用PIN碼。',
    ACS: 'ACS密碼',
    tip2: 'ACS密碼用於在線購買',
    expired: '過期',
    address: '地址',
  },

  guideDialog: {
    title: '如何使用您的卡片？',
    info: '如何獲取PIN碼和ACS密碼？',
    section1: '點擊查看PIN碼按鈕',
    section2: `可以查看卡片的PIN碼和ACS密碼`,
    section3: '場景1 - POS和ATM',
    section3_1: `使用POS或ATM時，您需要輸入PIN碼進行驗證`,
    section4: `場景2 - 線上購物`,
    section4_1: `在線購物時，您需要輸入您的ACS密碼。`,
  },

  userManual: {
    headerTitle: '用戶手冊',
    title: '用戶手冊',
    title1: '一般帳戶服務',
    fee: '費用',
    info1_1: '帳戶維護費（每張活躍卡）',
    info1_2: '/月',
    title2: '卡片',
    info2_1: '以歐元支付',
    info2_2: '以外幣支付',

    title3: '發現和相關服務',
    info3_1: '因餘額不足而拒絕卡付款',
    free: '免費',
    info3_2: '因超支、PIN碼或密文（CVV2）錯誤、卡片過期或被封鎖而拒絕卡付款',

    title4: '其他服務',
    info4_1: '匯款=卡片之間的轉賬',
    // info4_2: '在Paytend發行的您的Mastercard卡之間匯款',

    title5: `互聯網服務-WWW.PAYTEND.COM <我的帳戶>（不包括互聯網連接費`,
    info5_1: '操作和餘額查詢',
    info5_2: '支出控制',
    info5_3: '過去3個月的交易電子記錄',

    title6: '卡片限額',
    title6_1: '卡片',
    info6_1: '每天最大充值限額',
    info6_2: '隨時最大餘額',
    info6_3: '每月最大交易限額',
    info6_4: '每天最大卡付款限額',
    info6_5: '每筆ATM交易的最高限額',
    info6_6: '每日ATM提款限額',
    info6_7: 'ATM最低提款限額',

    title7: '充值',
    title7_1: '卡片（歐元）',
    info7_1: '充值費',
    info7_2: '最低充值金額',
    info7_3: '每天充值限額',
    info7_4: '每月充值限額',
    info7_5: '最大餘額',

    title8: '交易費',
    title8_1: '卡片（歐元）',
    info8_1: '在歐洲經濟區使用卡付款',
    info8_2: '在歐洲經濟區以外使用卡付款',
    info8_3: '2%，最低€0.60',

    title9: '取款費用',
    title9_1: '卡片（歐元）',
    info9_1: 'ATM取款費用',
    info9_2: '2%，最低€3.00',
    info9_3: 'ATM餘額查詢',
    info9_4: 'ATM餘額查詢',

    title10: '卡片有效',
    title10_1: '使用限制',
    title10_2: '36個月',

    info10_1: '自動加油泵*',
    info10_2: '不允許',
    info10_3: '電話/郵件付款*',
    info10_4: '不允許',
    info10_5: '定期付款*',
    info10_6: '不允許',
    info10_7: '*如果您想使用此功能，請聯繫我們。',
  },

  // 实体卡挂失和注销
  reportLoss: {
    title: '掛失',

    pleaseChoose: '請選擇',
    cancelCardSubmit: '註銷',
    cardNumber: '卡號',
    googleAuthenticatorCode: 'Google 驗證器代碼',
    btn: '繼續',
    backHome: '返回首页',
    succState: '掛失成功',
    succTip: '您的卡片掛失已完成。請在掛失解除前不要進行充值或消費。如有任何問題，請向客戶服務提供反饋，謝謝。',
    failedState: '掛失失敗',
    failTip: '由於卡片狀態已凍結，掛失報告失敗。請盡快聯繫客戶服務進行處理。謝謝。',

    reportedLost: '该卡已被挂失',
    reportedLostReason: '您的卡片挂失报告已完成。在挂失解除前，请勿充值或消费。',
    cancelBtn: '取消挂失',
    replacementBtn: '卡片更換',

    cancleSuss: '取消掛失成功',
    cancleSussReason: '您的掛失申請已成功取消，卡片可以正常使用。',
    cancleFail: '取消掛失失敗',
    cancleFailReason: '由於卡片可能被凍結，您的掛失申請失敗，請盡快聯繫客戶服務進行處理。',
  },

  // 实体卡转换
  replacement: {
    cardReplacement: '卡片更換',
    title: '卡片更換請求',
    tip_info: '請提供必要的信息',
    placeholder1: '更換卡片號碼',
    placeholder2: '更換卡片的CVV',
    placeholder3: '卡片更換的令牌',
    agree: '一旦提交卡片更換請求，此卡的餘額將轉移到提供的卡片上。',
    agree1: '提交卡片更換後，舊卡將被凍結，不能用於充值或提款等交易。請勿進行任何購買行為。',
    importantReminder: '重要提醒',
    tip_info2: '您是否要將此卡的全部餘額轉移到上面提供的卡片上？',
    cancel: '取消',
    confirm: '確認',
    state_title: '卡片更換提交成功。',
    tip_info3: '卡片更換請求已提交。在更換成功之前，請勿進行任何購買或充值。',
    state_title1: '卡片更換申請中。',
    state_info1: '卡片更換請求已提交。在更換成功之前，請勿進行任何購買或充值。',
    cardNumber: '卡號',
    tokenForCard: '卡片令牌',
  },

  cancelCard: {
    title: '註銷',
    title1: '請提交資訊',
    cardType: '卡類型',
    physicalCard: '實體卡',
    placeholder1: '您的卡號',
    placeholder2: '取消卡片原因',
    updateInfo: '您需要上傳一張您手持用於KYC的身份證件的照片。',
    selected1: '如果卡中的餘額不為零，則表示默認已放棄。',
    selected2: '一旦提交了卡取消请求，将無法進行進一步的交易，無法退款，取消后也無法恢復卡片。',
    confirm: '確認',

    cancelCardSus: '註銷成功',
    cancelCardSusRea: '您的卡片註銷請求已成功處理。請在註銷完成之前避免充值或進行任何購買。如果您有任何問題，請聯繫客戶服務以獲得協助。謝謝。',
    cancelCardTitle: '在卡片註銷申請中。',
    cancelCardTip1: `您的卡片損失報告已完成。`,
    cancelCardTip2: '請在挂失報告發布之前不要充值或消費。',
    backHome: '返回首页',

    cancelCardSucTitle: '已移除卡片。',
    cancelCardSucTip: '您已移除此卡。請勿再次使用它進行任何購買或退款，以避免觸發卡發行方的風險規則。',
  },

  submitRecord: {
    title: '提交記錄',
    submitType: '提交類型',
    cancelCard: '註銷',
    reportLoss: '掛失',
    releaseLossReport: '釋出損失報告',
    submitTime: '提交時間',
    submitResult: '提交結果',
    successful: '成功',
    failed: '失敗',
    inProcess: '處理中',
    no_tip: '未找到記錄。',
    loading: '載入中',
    noMore: '沒有更多~',
  },

  popover: {
    details: '詳情',
  },

  basicInformation: {
    title: '基本信息',
    phoneNumber: '電話號碼',
    firstName: '名字',
    lastName: '姓氏',
    gender: '性別',
    birthday: '生日',
    nationality: '國籍',
    male: '男',
    female: '女',
  },

  // 新增
  phyPaymentAmount: {
    title: '申請卡片',
    title1: '付款金額',
    rechargeAddress: '充值地址',
  },

  phyPaymentPadding: {
    title: '加密貨幣發送中...',
    title1: '實體卡',
    tip1: '付款成功',
    tip2: '申請成功，等待交付',
  },

  phyPaymentSuccess: {
    title: '申請成功！',
    title1: '實體卡',
    info1: '付款成功',
    info2: '申請成功，等待交付',
    info3: '申請成功，等待交付',
    cardHolder: '持卡人',
    balance: '餘額',
    issuingDate: '發行日期',
    btn: '查看訂單狀態',
  },

  frozenPage: {
    title: '您的帳戶已被凍結',
    failedReason: '凍結原因',
    title1: '卡片已凍結',
    tip1: '您的拒絕率超過30％，並且交易總數超過了10次。',
    tip2: '您的拒絕原因包括「餘額不足」，且持續發生超過10次。',
    tip3: '您的帳戶存在嚴重的交易風險並已被凍結。',
    tip4: '您的卡片已透支并超過了5美元。',
    tip5: '帳戶中的月費金額已連續三個月不足。',
  },

  overdrawn: {
    tip: '重要提醒：您的虛擬卡已透支',
    importantReminder: '重要提醒',
    tip1: '您的虛擬卡已透支，因此您無法申請新卡。請儘快充值。',
    btn: '继续充值',
  },

  cardLimitModal: {
    tip: '自2024年11月4日起，每個用戶只能申請總共 ',
    tip1: ' 張虛擬卡。您當前的卡片申請數量已達到限制。已經申請的卡片不會受到影響。',
  },

  details: {
    title: '交易詳情',
    businessName: '企業名稱',
    type: '類型',
    currency: '貨幣',
    billingAmount: '帳單金額',
    rate: '匯率',
    orderNumber: '訂單編號',
    orderTime: '訂單時間',
    transactionCountry: '交易國家',

    payment: '付款',
    atmWithdraw: 'ATM 提款',
    adjustment: '結算調整',
    balanceChecking: '在自動提款機查詢餘額',
    monthlyFee: '月費',
    success: '成功',
  },

  order: {
    recharge: '充值',
    withdraw: '贖回',
    transfer: '轉賬',
    recharge_tip1: '你還沒有充值',
    recharge_tip2: '請完成首次充值以激活卡片',
    withdraw_tip1: '你還未取款',
    recharge_title: '充值記錄',
    withdraw_title: '贖回記錄',
  },

  notice: {
    title: '親愛的用戶，',
    info1: '為了確保服務性能和安全性，我們的發卡銀行將進行系統維護。在維護期間，以下服務將暫時無法使用：',
    info2: '* 卡片相關服務（例如交易、餘額查詢）',
    info3: '* 特定的支付和購買功能。您的資產安全是我們的首要任務；在維護期間不會有損失或風險 ',
    info4: '預計維護時間：大約24小時。',
    btn: '確認',
    infoNew: '銀行正在進行系統維護，部分虛擬卡服務和交易可能暫時受到影響。請放心，您的資金完全安全，不會受到影響。在我們努力解決問題時，請耐心等待。',
    tipNotice: '銀行正在進行系統維護',
    titleNotice: '通知',

    title5: '卡片已被取消。您的卡片已被取消。请不要发起任何消费退款。您无法收到此卡的任何退款。',
    info5: '由於觸發了多個風險控制規則，風險水平增加，促使我們實施限制措施。',
    info5_1: '請刪除該卡片並提取您的資金。',
    del_btn: '刪除卡片並贖回',
    unfrozenBtn: '解凍並提交',
    depositAndNnfreeze: '存款和解凍',
    pleaseDeposit: '请存款',
    depositTip1: '您的帳戶處於透支狀態。請充值超過 ',
    depositTip1_1: ' 美元以解凍。',
    depositBtn: '前往充值',
    tipTitle: '請閱讀並理解以下風險情境',
    tipTitle1_1: '請閱讀並理解以下風險控制規則',
    tipTitle1: '我已經了解並承諾不觸發上述高風險情境',
    tipTitle2: '我已瞭解並承諾遵守以上風險規則',
    warning: '警告',
    tipInfo1: '如果您再次觸發上述風險（高風險金融風險情景和風險控制規則），您的卡將被取消。',
    tipInfo2: '请确保您遵守风险规则。',
    submitBtn: '同意并提交',

    kyc_frozen_tip: '很遺憾地通知您，您的KYC驗證未通過。根據國際金融監管要求，我們無法為您提供服務。如果您的帳戶中有餘額，請立即提取。您在我們這裡的卡片將在2周後被凍結。感謝您的理解和合作。',

    overdraftTip: '請充值您的帳戶金額超過 ',
    overdraftTip1: ' 美元。',
  },

  kycState: {
    kycFailTitle: '您的KYC验证未通过',
    kycResults: 'KYC結果',
    kycInfo: '您的KYC验证未通过。',
    btn1: '返回首页',
    kycSuccessTitle: '身份验证成功',
    kycSuccessInfo: '恭喜！所有提交的文件通过了验证过程。恭喜！所有提交的文件通过了验证过程。',
    next: '下一步',
  },

  prohibit: {
    importantReminder: '重要提醒',
    info: '我們檢測到您目前的IP位置位於我們服務受限的地區。不幸的是，基於當地的法律和規定，我們暫時無法為您提供服務。',
    info1: '對於可能造成的不便，我們深感抱歉。如果您不是來自受限地區的用戶，請在無限制地區使用我們的平台並進行KYC驗證，以確認您的國籍和身份。',
    btn: '返回首页',
  },

  inputErrTip: {
    tip: '請填寫所有欄位並提供有效資訊',
    verify: '驗證',
  },

  selectInput: {
    searchInput_placeholder: '在這裡搜索...',
    title: '請選擇',
  },

  homeAirdrop: {
    inactive: '未啟用',
    expire: '到期:',
    roule1: '1. 通過完成任意金額的存款來激活空投卡。',
    roule2: '2. 在激活之前，空投卡無法提取和使用。',
    roule3: '3. 如果在1個月內未激活空投卡，將被移除。',
    notice1: '完成充值以啟用空投卡。',
  },
};
export default zh;
